var dataSet = [{"English Words":"Able person","Parts of Speech":"","Tamil Words":"kettika:ran","Irula Words":"kettikala:","Toda Words":"","Meaning":"Someone who is skilled (at a particular task)"},
{"English Words":"After coming ","Parts of Speech":"","Tamil Words":"vanthapiraku","Irula Words":"vanta:me:","Toda Words":"","Meaning":"Come after in time"},
{"English Words":"Algae","Parts of Speech":"NOUN","Tamil Words":"pa:cam","Irula Words":"patta","Toda Words":"","Meaning":"A simple, non-flowering, and typically aquatic plant of a large assemblage that includes the seaweeds and many single-celled forms"},
{"English Words":"All","Parts of Speech":"ADVERB","Tamil Words":"aṉaittum","Irula Words":"attani","Toda Words":"eltk","Meaning":"Used to refer to the whole quantity."},
{"English Words":"Am coming","Parts of Speech":"","Tamil Words":"varukire;in","Irula Words":"varuke:mu","Toda Words":"","Meaning":""},
{"English Words":"Am here","Parts of Speech":"","Tamil Words":"irukkire:n","Irula Words":"irukke:","Toda Words":"i:nk","Meaning":""},
{"English Words":"Anger","Parts of Speech":"NOUN","Tamil Words":"ko:pam","Irula Words":"ko:pa","Toda Words":"pu:c","Meaning":"A strong feeling of annoyance, displeasure, or hostility"},
{"English Words":"Angry","Parts of Speech":"ADJECTIVE","Tamil Words":"ko:pam","Irula Words":"vecepa","Toda Words":"muro","Meaning":"Feeling or showing strong annoyance, displeasure, or hostility; full of anger"},
{"English Words":"Ant","Parts of Speech":"NOUN","Tamil Words":"erumpu","Irula Words":"urumpu","Toda Words":"irb","Meaning":"A small insect typically having a sting and living in a complex social colony with one or more breeding queens"},
{"English Words":"Another","Parts of Speech":"DETERMINER & PRONOUN","Tamil Words":"maṟṟoru","Irula Words":"","Toda Words":"inwiḏ","Meaning":"Used to refer to a different person or thing from one already mentioned or known about"},
{"English Words":"Apricot","Parts of Speech":"NOUN","Tamil Words":"ilantai","Irula Words":"lantaippaḻam","Toda Words":"","Meaning":"A juicy, soft fruit of an orange-yellow colour resembling a small peach"},
{"English Words":"Are calling","Parts of Speech":"","Tamil Words":"ku:ppitukira","Irula Words":"lekka;","Toda Words":"","Meaning":""},
{"English Words":"Are going","Parts of Speech":"","Tamil Words":"po:yirukire:in","Irula Words":"po:gemu","Toda Words":"","Meaning":""},
{"English Words":"Are you coming","Parts of Speech":"","Tamil Words":"varukira:ya: ","Irula Words":"varkala:","Toda Words":"","Meaning":""},
{"English Words":"Arm ","Parts of Speech":"NOUN","Tamil Words":"kai","Irula Words":"keyyi","Toda Words":"","Meaning":"Each of the two upper limbs of the human body from the shoulder to the hand."},
{"English Words":"Ashes","Parts of Speech":"NOUN","Tamil Words":"ca:mbal","Irula Words":"kukke: ","Toda Words":"pu:dhi","Meaning":"The powdery residue left after the burning of a substance."},
{"English Words":"Ask ","Parts of Speech":"VERB","Tamil Words":"ke:l","Irula Words":"ke:lu","Toda Words":"","Meaning":"Say something in order to obtain an answer or some information."},
{"English Words":"Ate ","Parts of Speech":"VERB","Tamil Words":"ca:ppitta:ru","Irula Words":"tinta:ru","Toda Words":"","Meaning":"Past of eat (put (food) into the mouth and chew and swallow it)"},
{"English Words":"Apple ","Parts of Speech":"NOUN","Tamil Words":"a:ppiḷ","Irula Words":"a:pil","Toda Words":"api:l","Meaning":"The round fruit of a tree of the rose family, which typically has thin green or red skin and crisp flesh."},
{"English Words":"Auction","Parts of Speech":"NOUN","Tamil Words":"e:lam","Irula Words":"","Toda Words":"e:lam","Meaning":"A public sale in which goods or property are sold to the highest bidder"},
{"English Words":"Always","Parts of Speech":"ADVERB","Tamil Words":"eppo:tum","Irula Words":"","Toda Words":"e:fakm","Meaning":"At all times; on all occasions."},
{"English Words":"A place for keeing pot","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aḍṇguḏy","Meaning":""},
{"English Words":"Bamboo Tree","Parts of Speech":"NOUN","Tamil Words":"tappe: ","Irula Words":"dabbe, patte: ","Toda Words":"","Meaning":"The hard or woody, jointed, often hollow stems of these plants, used in construction and to make various kinds of utensils."},
{"English Words":"Bangle ","Parts of Speech":"NOUN","Tamil Words":"valayal","Irula Words":"kaikale","Toda Words":"","Meaning":"A rigid bracelet or anklet"},
{"English Words":"Barrel","Parts of Speech":"NOUN","Tamil Words":"aṇṭa:","Irula Words":"aNṭa:vu","Toda Words":"","Meaning":"A cylindrical container bulging out in the middle, traditionally made of wooden staves with metal hoops round them"},
{"English Words":"Bat ","Parts of Speech":"NOUN","Tamil Words":"vavva:l","Irula Words":"vevva:lu","Toda Words":"","Meaning":"A mainly nocturnal mammal capable of sustained flight, with membranous wings that extend between the fingers and limbs"},
{"English Words":"Bathe","Parts of Speech":"NOUN","Tamil Words":"kuḷi","Irula Words":"taiya:ṭu","Toda Words":"","Meaning":"Wash by immersing one's body in water"},
{"English Words":"Beak ","Parts of Speech":"NOUN","Tamil Words":"alaku","Irula Words":"kokku","Toda Words":"","Meaning":"A bird's horny projecting jaws; a bill"},
{"English Words":"Beetroot","Parts of Speech":"NOUN","Tamil Words":"pi:ṭru:ṭ","Irula Words":"piiṭruṭṭi","Toda Words":"","Meaning":"The edible dark-red spherical root of a kind of beet, eaten as a vegetable"},
{"English Words":"Big","Parts of Speech":"ADJECTIVE","Tamil Words":"periya","Irula Words":"bellathu","Toda Words":"etu:ḍpe","Meaning":"Of considerable size, extent, or intensity"},
{"English Words":"big boy","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"etu:ḍ mox","Meaning":""},
{"English Words":"Bite","Parts of Speech":"ADJECTIVE","Tamil Words":"katittukko, katittukkol","Irula Words":"katuttukko, kaduttukko:","Toda Words":"koc","Meaning":"Able to wound the skin with a sting or fangs"},
{"English Words":"Black Monkey","Parts of Speech":"","Tamil Words":"manti","Irula Words":"menti","Toda Words":"","Meaning":""},
{"English Words":"Blackberry","Parts of Speech":"NOUN","Tamil Words":"na:val maram","Irula Words":"nakkaappaḻa maram","Toda Words":"","Meaning":"An edible soft fruit consisting of a cluster of soft purple-black drupelets"},
{"English Words":"Blood ","Parts of Speech":"NOUN","Tamil Words":"irattam, rattam","Irula Words":"irette, ratte:,  latte, ratte, tattam , rattam","Toda Words":"nets","Meaning":"The red liquid that circulates in the arteries and veins of humans and other vertebrate animals, carrying oxygen to and carbon dioxide from the tissues of the body"},
{"English Words":"Body","Parts of Speech":"NOUN","Tamil Words":"uṭal","Irula Words":"oṭampu","Toda Words":"","Meaning":"The physical structure, including the bones, flesh, and organs, of a person or an animal"},
{"English Words":"Bone","Parts of Speech":"NOUN","Tamil Words":"elumpu","Irula Words":"kappa:gu","Toda Words":"eṭf","Meaning":"Any of the pieces of hard, whitish tissue making up the skeleton in humans and other vertebrates"},
{"English Words":"Brain","Parts of Speech":"NOUN","Tamil Words":"mu:ḷai","Irula Words":"mu:le","Toda Words":"mu:ly","Meaning":"An organ of soft nervous tissue contained in the skull of vertebrates, functioning as the coordinating centre of sensation and intellectual and nervous activity"},
{"English Words":"Brother","Parts of Speech":"NOUN","Tamil Words":"aṇṇaṉ","Irula Words":"pelava","Toda Words":"","Meaning":"A man or boy in relation to other sons and daughters of his parents"},
{"English Words":"Brother in law","Parts of Speech":"NOUN","Tamil Words":"macca:n","Irula Words":"macc:a, macca:n","Toda Words":"","Meaning":"The brother of one's wife or husband"},
{"English Words":"Bucket","Parts of Speech":"NOUN","Tamil Words":"vali ","Irula Words":"vaiyyi , vaiyyu ","Toda Words":"","Meaning":"A roughly cylindrical open container, typically made of metal or plastic, with a handle, used to hold and carry liquids or other material"},
{"English Words":"Buffalo","Parts of Speech":"NOUN","Tamil Words":"erumai","Irula Words":"erume","Toda Words":"irrh","Meaning":"A heavily built wild ox with backward-curving horns"},
{"English Words":"Burn material","Parts of Speech":"","Tamil Words":"ca:mbal ","Irula Words":"ca;mba, kukke","Toda Words":"","Meaning":"A material that burns easily"},
{"English Words":"Burp","Parts of Speech":"VERB","Tamil Words":"e:ppam","Irula Words":"ṭeppa:","Toda Words":"","Meaning":"Noisily release air from the stomach through the mouth; belch"},
{"English Words":"Butterfly","Parts of Speech":"NOUN","Tamil Words":"paṭṭa:m pucci","Irula Words":"viNRu","Toda Words":"","Meaning":"A nectar-feeding insect with two pairs of large, typically brightly coloured wings that are covered with microscopic scales"},
{"English Words":"Button","Parts of Speech":"NOUN","Tamil Words":"pitta:n","Irula Words":"pitta:","Toda Words":"","Meaning":"A small disk or knob sewn onto a garment, either to fasten it by being pushed through a slit made for the purpose, or for decoration"},
{"English Words":"By me","Parts of Speech":"","Tamil Words":"enna:l","Irula Words":"enna:le, emuthuna:le","Toda Words":"","Meaning":""},
{"English Words":"By us","Parts of Speech":"","Tamil Words":"enkal:l","Irula Words":"emukku","Toda Words":"","Meaning":""},
{"English Words":"Bull","Parts of Speech":"NOUN","Tamil Words":"ka:lai ma:ṭu","Irula Words":"","Toda Words":"est","Meaning":"An uncastrated male bovine animal."},
{"English Words":"big potatoes","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"ittu:dki:siye:","Meaning":""},
{"English Words":"bean","Parts of Speech":"NOUN","Tamil Words":"pi:ṉs","Irula Words":"","Toda Words":"efir","Meaning":"An edible seed, typically kidney-shaped, growing in long pods on certain leguminous plants"},
{"English Words":"boundary","Parts of Speech":"NOUN","Tamil Words":"ellai","Irula Words":"","Toda Words":"ely","Meaning":"A line which marks the limits of an area; a dividing line."},
{"English Words":"banyan tree","Parts of Speech":"NOUN","Tamil Words":"a:lamaram","Irula Words":"","Toda Words":"a:lme:ṇ","Meaning":"An Indian fig tree, the branches of which produce wide-ranging aerial roots which later become accessory trunks."},
{"English Words":"bandicoot","Parts of Speech":"NOUN","Tamil Words":"perucca:ḷi","Irula Words":"","Toda Words":"egan","Meaning":"A mainly insectivorous marsupial."},
{"English Words":"beautiful","Parts of Speech":"ADJECTIVE","Tamil Words":"aḻaka:ṉa","Irula Words":"","Toda Words":"eṭy","Meaning":"Pleasing the senses or mind aesthetically."},
{"English Words":"bankle","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"ats","Meaning":""},
{"English Words":"black","Parts of Speech":"ADJECTIVE","Tamil Words":"karuppu","Irula Words":"","Toda Words":"ka:g","Meaning":"The very darkest colour owing to the absence of or complete absorption of light; the opposite of white."},
{"English Words":"blue","Parts of Speech":"ADJECTIVE","Tamil Words":"ni:lam","Irula Words":"","Toda Words":"ni:lm","Meaning":"A colour intermediate between green and violet, as of the sky or sea on a sunny day."},
{"English Words":"bite","Parts of Speech":"VERB","Tamil Words":"kaṭikka","Irula Words":"adititto: ","Toda Words":"","Meaning":"Use the teeth to cut into (something)."},
{"English Words":"Cabbage","Parts of Speech":"NOUN","Tamil Words":"muṭaiko:s","Irula Words":"muṭṭakecu","Toda Words":"","Meaning":"A cultivated plant eaten as a vegetable, having thick green or purple leaves surrounding a spherical heart or head of young leaves"},
{"English Words":"Calf","Parts of Speech":"NOUN","Tamil Words":"kaṉṟu","Irula Words":"kaṇtu","Toda Words":"","Meaning":"A young bovine animal, especially a domestic cow or bull in its first year"},
{"English Words":"calf (buffalo)","Parts of Speech":"NOUN","Tamil Words":"kaṉṟu","Irula Words":"","Toda Words":"kor","Meaning":"A young bovine animal, especially a domestic buffalo or bull in its first year"},
{"English Words":"Came","Parts of Speech":"VERB","Tamil Words":"vantha:n, vanta:rkal","Irula Words":"vantutta:, vantara:","Toda Words":"pod","Meaning":"Simple past tense of come"},
{"English Words":"Can be scar","Parts of Speech":"","Tamil Words":"terikiratu","Irula Words":"terikutu","Toda Words":"","Meaning":""},
{"English Words":"Can i come","Parts of Speech":"","Tamil Words":"varalama:","Irula Words":"varukuta:","Toda Words":"","Meaning":""},
{"English Words":"Caste ","Parts of Speech":"NOUN","Tamil Words":"ca:ti","Irula Words":"karṭika:, kuplika:, kuruneeka:ru, peraka:raru, a:rumuuppu, campa:ru, vellaka:","Toda Words":"","Meaning":"Each of the hereditary classes of Hindu society, distinguished by relative degrees of ritual purity or pollution and of social status"},
{"English Words":"Cat","Parts of Speech":"NOUN","Tamil Words":"pu:ṉai","Irula Words":"piine","Toda Words":"kwaty ","Meaning":"A small domesticated carnivorous mammal with soft fur, a short snout, and retractile claws"},
{"English Words":"Caterpillar ","Parts of Speech":"NOUN","Tamil Words":"kampaḷip pu:cci","Irula Words":"kampaLippuḻuvu","Toda Words":"","Meaning":"The larva of a butterfly or moth, which has a segmented body resembling a worm with three pairs of true legs and several pairs of leg-like appendages"},
{"English Words":"Centipede","Parts of Speech":"NOUN","Tamil Words":"pu:ra:ṇ","Irula Words":"kaṅkuṉi","Toda Words":"","Meaning":"A predatory myriapod invertebrate with a flattened elongated body composed of many segments"},
{"English Words":"Chameleon","Parts of Speech":"NOUN","Tamil Words":"o:ṇa:ṉ","Irula Words":"ootti","Toda Words":"","Meaning":"A small slow-moving Old World lizard with a prehensile tail, long extensible tongue, protruding eyes that rotate independently, and a highly developed ability to change colour"},
{"English Words":"Change","Parts of Speech":"VERB","Tamil Words":"ma:rru","Irula Words":"ta:itti","Toda Words":"","Meaning":"Make or become different"},
{"English Words":"Chase","Parts of Speech":"VERB","Tamil Words":"turattu","Irula Words":"tura:tiru, muṭukku","Toda Words":"","Meaning":"Pursue in order to catch or catch up with"},
{"English Words":"Chicken","Parts of Speech":"NOUN","Tamil Words":"ko:ḻi kuñcu","Irula Words":"kooyikkiñcu","Toda Words":"","Meaning":"A domestic fowl kept for its eggs or meat, especially a young one"},
{"English Words":"Children","Parts of Speech":"NOUN","Tamil Words":"ciṟuvaṉ, ciṟumi","Irula Words":"citta:lu","Toda Words":"pupup","Meaning":"Plural form of child (a young human being below the age of puberty or below the legal age of majority)"},
{"English Words":"Chin","Parts of Speech":"NOUN","Tamil Words":"kaṇṇam","Irula Words":"keNNa, pakuṭu","Toda Words":"mo:s","Meaning":"The protruding part of the face below the mouth, formed by the apex of the lower jaw"},
{"English Words":"chief village","Parts of Speech":"NOUN","Tamil Words":"talaiver","Irula Words":"u:r mu:ppen","Toda Words":"etu:ḍ moḍ","Meaning":"A man on who head of th village "},
{"English Words":"Chop ","Parts of Speech":"VERB","Tamil Words":"uṭai","Irula Words":"ṭetturu","Toda Words":"","Meaning":"Cut (something) into pieces with repeated sharp blows of an axe or knife"},
{"English Words":"Close","Parts of Speech":"ADJECTIVE","Tamil Words":"mu:ṭu","Irula Words":"oṭṭu","Toda Words":"art","Meaning":"Only a short distance away or apart in space or time"},
{"English Words":"Cockerel","Parts of Speech":"NOUN","Tamil Words":"ceval","Irula Words":"ca:va","Toda Words":"","Meaning":"A young domestic cock"},
{"English Words":"Cockroach ","Parts of Speech":"NOUN","Tamil Words":"karappa:ṉ","Irula Words":"pa:cca","Toda Words":"pa:t","Meaning":"A beetle-like scavenging insect with long antennae and legs"},
{"English Words":"Comb/ Crest/ Hair Bun","Parts of Speech":"NOUN","Tamil Words":"koṇṭai","Irula Words":"koNṭe","Toda Words":"","Meaning":"A comb or tuft of feathers, fur, or skin on the head of a bird or other animal"},
{"English Words":"Come ","Parts of Speech":"VERB","Tamil Words":"va:","Irula Words":"va:","Toda Words":"","Meaning":"Move or travel towards or into a place thought of as near or familiar to the speaker"},
{"English Words":"Comes","Parts of Speech":"VERB","Tamil Words":"varunkal","Irula Words":"va:yi","Toda Words":"","Meaning":"Move or travel towards or into a place thought of as near or familiar to the speaker"},
{"English Words":"Cool ","Parts of Speech":"ADJECTIVE","Tamil Words":"kulirci ","Irula Words":"viruvira, a:rna;du, kulukak, kuluru, kulukaka","Toda Words":"","Meaning":"Of or at a fairly low temperature"},
{"English Words":"Cough","Parts of Speech":"VERB","Tamil Words":"irumal","Irula Words":"keruma:","Toda Words":"","Meaning":"Expel air from the lungs with a sudden sharp sound"},
{"English Words":"Courage","Parts of Speech":"NOUN","Tamil Words":"tairiyam","Irula Words":"teiyriya","Toda Words":"eoy","Meaning":"The ability to do something that frightens one; bravery"},
{"English Words":"Crab ","Parts of Speech":"NOUN","Tamil Words":"naṇṭu","Irula Words":"neNṭu","Toda Words":"","Meaning":"A crustacean, found chiefly on seashores, with a broad carapace, stalked eyes, and five pairs of legs, the first pair of which are modified as pincers"},
{"English Words":"Crow","Parts of Speech":"NOUN","Tamil Words":"ka:kam","Irula Words":"ka:ka:yi","Toda Words":"ka:k","Meaning":"A large perching bird with mostly glossy black plumage, a heavy bill, and a raucous voice"},
{"English Words":"Cry ","Parts of Speech":"VERB","Tamil Words":"aḻu, aḻukai","Irula Words":"la:ru, la:ruke, e:natu","Toda Words":"","Meaning":"Shed tears in distress, pain, or sorrow"},
{"English Words":"Crying ","Parts of Speech":"ADJECTIVE","Tamil Words":"alukai","Irula Words":"la:rge","Toda Words":"","Meaning":"Very great"},
{"English Words":"Cymbal","Parts of Speech":"NOUN","Tamil Words":"ja:lara:","Irula Words":"ja:lra:","Toda Words":"","Meaning":"A musical instrument consisting of a slightly concave round brass plate which is either struck against another one or struck with a stick to make a ringing or clashing sound"},
{"English Words":"Clean","Parts of Speech":"ADJECTIVE","Tamil Words":"Cuttama:ṉa","Irula Words":"","Toda Words":"oruvu:","Meaning":"Free from dirt, marks, or stains."},
{"English Words":"Cow dung","Parts of Speech":"NOUN","Tamil Words":"ma:ṭṭu ca:ṇam","Irula Words":"","Toda Words":"a:py","Meaning":"The excrement of animals; manure"},
{"English Words":"cotton","Parts of Speech":"NOUN","Tamil Words":"parutti","Irula Words":"","Toda Words":"aty","Meaning":"A soft white fibrous substance which surrounds the seeds of the cotton plant and is made into textile fibre and thread for sewing."},
{"English Words":"curd","Parts of Speech":"NOUN","Tamil Words":"tayir","Irula Words":"","Toda Words":"arḍporh","Meaning":"A soft, white substance formed when milk coagulates, used as the basis for cheese."},
{"English Words":"cating plate","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"korstarh","Meaning":""},
{"English Words":"Death ","Parts of Speech":"NOUN","Tamil Words":"irappu","Irula Words":"tettu","Toda Words":"","Meaning":"The action or fact of dying or being killed; the end of the life of a person or organism."},
{"English Words":"Dhoti ","Parts of Speech":"NOUN","Tamil Words":"ve:ṭṭi","Irula Words":"muṉṭu","Toda Words":"tarph","Meaning":"The state of being dead"},
{"English Words":"Did they come","Parts of Speech":"","Tamil Words":"vantarkala: ","Irula Words":"vanthara:","Toda Words":"","Meaning":"A garment worn by male Hindus, consisting of a piece of material tied around the waist and extending to cover most of the legs"},
{"English Words":"Die ","Parts of Speech":"VERB","Tamil Words":"cattu, cettuvidu","Irula Words":"cettu, cetru","Toda Words":"","Meaning":"(of a person, animal, or plant) stop living."},
{"English Words":"Difficult (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"kastam","Irula Words":"Kasta: ","Toda Words":"","Meaning":"Needing much effort or skill to accomplish, deal with, or understand"},
{"English Words":"Dig ","Parts of Speech":"VERB","Tamil Words":"to:ṇṭu","Irula Words":"kalli","Toda Words":"aḍo","Meaning":"Break up and move earth with a tool or machine, or with hands, paws, snout, et"},
{"English Words":"Divide (v)","Parts of Speech":"VERB","Tamil Words":"vakuttu","Irula Words":"varanthu, ,va:tti,kantu","Toda Words":"","Meaning":"Separate or be separated into parts"},
{"English Words":"Dog (n)","Parts of Speech":"NOUN","Tamil Words":"na:y","Irula Words":"na:iy , na:yi, na:iy ","Toda Words":"","Meaning":"A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, non-retractile claws, and a barking, howling, or whining voice"},
{"English Words":"Don’t talk","Parts of Speech":"","Tamil Words":"pe:ca:te:","Irula Words":"pecute: ","Toda Words":"","Meaning":""},
{"English Words":"Donkey (n)","Parts of Speech":"NOUN","Tamil Words":"kaḻutai","Irula Words":"kelute, kaḻutee","Toda Words":"","Meaning":"A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass"},
{"English Words":"Dove (n)","Parts of Speech":"NOUN","Tamil Words":"oura; ","Irula Words":"para:, para ","Toda Words":"","Meaning":"A stocky bird with a small head, short legs, and a cooing voice, feeding on seeds or fruit"},
{"English Words":"Down (adv)","Parts of Speech":"ADVERB","Tamil Words":"iṟaṅku","Irula Words":"aṭiRaṅku, aṭira:ṅka","Toda Words":"","Meaning":"Towards or in a lower place or position, especially to or on the ground or another surface"},
{"English Words":"Drum (n)","Parts of Speech":"NOUN","Tamil Words":"mattaḷam","Irula Words":"pore, tavulu","Toda Words":"","Meaning":"A percussion instrument sounded by being struck with sticks or the hands, typically cylindrical, barrel-shaped, or bowl-shaped, with a taut membrane over one or both ends"},
{"English Words":"Dung (n)","Parts of Speech":"NOUN","Tamil Words":"ca:ṇam","Irula Words":"reṭṭi, caaṇi","Toda Words":"","Meaning":"The excrement of animals; manure"},
{"English Words":"Design used in dress","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"puho:r","Meaning":""},
{"English Words":"dowry","Parts of Speech":"NOUN","Tamil Words":"varataṭciṉai","Irula Words":"","Toda Words":"aṟpitir","Meaning":"An amount of property or money brought by a bride to her husband on their marriage."},
{"English Words":"desire","Parts of Speech":"NOUN","Tamil Words":"a:cai","Irula Words":"","Toda Words":"a:sy","Meaning":"A strong feeling of wanting to have something or wishing for something to happen."},
{"English Words":"door","Parts of Speech":"NOUN","Tamil Words":"katavu","Irula Words":"","Toda Words":"pora:rh","Meaning":"A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle, or in the framework of a cupboard."},
{"English Words":"Darkness","Parts of Speech":"NOUN","Tamil Words":"iruḷ","Irula Words":"","Toda Words":"e:ḷhkakar","Meaning":"The partial or total absence of light."},
{"English Words":"Eagle (n)","Parts of Speech":"NOUN","Tamil Words":"paruntu","Irula Words":"pa:ru","Toda Words":"pao","Meaning":"A large bird of prey with a massive hooked bill and long broad wings, known for its keen sight and powerful soaring fligh"},
{"English Words":"Ear (n)","Parts of Speech":"NOUN","Tamil Words":"ka:tu","Irula Words":"meeru","Toda Words":"kify","Meaning":"The organ of hearing and balance in humans and other vertebrates, especially the external part of this"},
{"English Words":"East (n)","Parts of Speech":"NOUN","Tamil Words":"kilakke","Irula Words":"Kela:kke","Toda Words":"","Meaning":"One of the four cardinal directions or points of the compass."},
{"English Words":"Eat (v)","Parts of Speech":"VERB","Tamil Words":"ca:ppidu","Irula Words":"tinṭu, tinnu","Toda Words":"ti:d","Meaning":"Put (food) into the mouth and chew and swallow it"},
{"English Words":"Egg (n)","Parts of Speech":"NOUN","Tamil Words":"muṭṭai","Irula Words":"mute, mutte, muṭṭee","Toda Words":"muty","Meaning":"An oval or round object laid by a female bird, reptile, fish, or invertebrate, usually containing a developing embryo."},
{"English Words":"Elder mother","Parts of Speech":"","Tamil Words":"peryamma:","Irula Words":"periyaavke , peryamma:, periya akke","Toda Words":"tyafa:","Meaning":""},
{"English Words":"Elder sister","Parts of Speech":"","Tamil Words":"akka:","Irula Words":"akke, akka:, akka;","Toda Words":"ok","Meaning":""},
{"English Words":"Elephant (n)","Parts of Speech":"NOUN","Tamil Words":"ya:ṉai","Irula Words":"aane","Toda Words":"a:n","Meaning":"A very large plant-eating mammal with a prehensile trunk, long curved ivory tusks, and large ears, native to Africa and southern Asia"},
{"English Words":"Essence (n)","Parts of Speech":"NOUN","Tamil Words":"racam","Irula Words":"raca: ","Toda Words":"","Meaning":"The intrinsic nature or indispensable quality of something, especially something abstract, which determines its character"},
{"English Words":"Extinguish (v)","Parts of Speech":"VERB","Tamil Words":"aṉai","Irula Words":"keṭuttiṭu","Toda Words":"","Meaning":"Put an end to; destroy"},
{"English Words":"Eye (n)","Parts of Speech":"NOUN","Tamil Words":"kan","Irula Words":"kannu, kan, kaNNu","Toda Words":"koṇ","Meaning":"Each of a pair of globular organs of sight in the head of humans and vertebrate animals"},
{"English Words":"Eye lid","Parts of Speech":"","Tamil Words":"imai","Irula Words":"imme","Toda Words":"","Meaning":"A thin fold of skin that covers and protects the human eye"},
{"English Words":"Eyebrow","Parts of Speech":"NOUN","Tamil Words":"puruvam","Irula Words":"puruva:","Toda Words":"","Meaning":"The strip of hair growing on the ridge above a person's eye socket"},
{"English Words":"Eyelash","Parts of Speech":"","Tamil Words":"imai","Irula Words":"eme","Toda Words":"","Meaning":"Each of the short curved hairs growing on the edges of the eyelids, serving to protect the eyes from dust"},
{"English Words":"enemy","Parts of Speech":"NOUN","Tamil Words":"etiri","Irula Words":"","Toda Words":"axexo:ṟn","Meaning":"A person who is actively opposed or hostile to someone or something."},
{"English Words":"evening","Parts of Speech":"NOUN","Tamil Words":"ca:yaṅka:lam","Irula Words":"","Toda Words":"ekaṟfots","Meaning":"The period of time at the end of the day."},
{"English Words":"experience","Parts of Speech":"NOUN","Tamil Words":"aṉupavam","Irula Words":"","Toda Words":"anbo:fm","Meaning":"Practical contact with and observation of facts or events."},
{"English Words":"Fast (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"c:kkaram/viraivu","Irula Words":"vagama","Toda Words":"","Meaning":"Moving or capable of moving at high speed"},
{"English Words":"Fat (n)","Parts of Speech":"NOUN","Tamil Words":"koḻuppu/kuṇṭu/uṭal parumaṉ","Irula Words":"koppu, kolupu, kolp","Toda Words":"","Meaning":"A natural oily substance occurring in animal bodies, especially when deposited as a layer under the skin or around certain organs"},
{"English Words":"Father (n)","Parts of Speech":"NOUN","Tamil Words":"tantai/appa:","Irula Words":"tante, amme, appa: ","Toda Words":"in","Meaning":"A man in relation to his child or children"},
{"English Words":"Father-in-law (n)","Parts of Speech":"NOUN","Tamil Words":"maṉaiviyiṉ appa:/ kaṇavaṉiṉ appa:","Irula Words":"ma:me","Toda Words":"","Meaning":"The father of one's husband or wife"},
{"English Words":"Fear (n)","Parts of Speech":"NOUN","Tamil Words":"payam","Irula Words":"baya","Toda Words":"","Meaning":"An unpleasant emotion caused by the threat of danger, pain, or harm"},
{"English Words":"Feathers (n)","Parts of Speech":"NOUN","Tamil Words":"iṟaku","Irula Words":"rr:kkatti, rekke, rake","Toda Words":"tu:fy","Meaning":"any of the flat appendages growing from a bird's skin and forming its plumage, consisting of a partly hollow horny shaft fringed with vanes of barbs"},
{"English Words":"Fell down (v)","Parts of Speech":"","Tamil Words":"ki:ḻe: viḻuntu","Irula Words":"lettu","Toda Words":"","Meaning":"A distressing emotion aroused by impending danger, evil, pain, etc."},
{"English Words":"Festival (n)","Parts of Speech":"NOUN","Tamil Words":"tiruviḻa:","Irula Words":"noompi","Toda Words":"","Meaning":"A day or period of celebration, typically for religious reasons"},
{"English Words":"Fever (n)","Parts of Speech":"NOUN","Tamil Words":"ka:yccal","Irula Words":"ppaṉi, keccalu","Toda Words":"e:f","Meaning":"An abnormally high body temperature, usually accompanied by shivering, headache, and in severe instances, delirium"},
{"English Words":"Fill (v)","Parts of Speech":"VERB","Tamil Words":"nirappu","Irula Words":"reppu","Toda Words":"","Meaning":"Cause (a space or container) to become full or almost full"},
{"English Words":"Finger ring (Toering) (n)","Parts of Speech":"","Tamil Words":"meṭṭi","Irula Words":"viñci","Toda Words":"","Meaning":"A ring made out of metals and non-metals worn on any of the toes"},
{"English Words":"Fire-fly ","Parts of Speech":"NOUN","Tamil Words":"miṉmiṉap pu:cci","Irula Words":"miṉnakku:ci","Toda Words":"","Meaning":"A soft-bodied beetle related to the glow-worm, the winged male and flightless female of which both have luminescent organs"},
{"English Words":"Fish","Parts of Speech":"NOUN","Tamil Words":"mi:ṉ","Irula Words":"me:n, me:nu, miiṉu","Toda Words":"","Meaning":"A limbless cold-blooded vertebrate animal with gills and fins living wholly in water"},
{"English Words":"Fly (v)","Parts of Speech":"VERB","Tamil Words":"i:","Irula Words":"eepi","Toda Words":"i:py","Meaning":"Travel through the air"},
{"English Words":"Follow (v)","Parts of Speech":"VERB","Tamil Words":"Piṉpaṟṟavum/piṉtoṭar","Irula Words":"pintukkuva:","Toda Words":"","Meaning":"Go or come after"},
{"English Words":"Foot","Parts of Speech":"NOUN","Tamil Words":"pa:tam","Irula Words":"","Toda Words":"o:thi","Meaning":""},
{"English Words":"Food (n)","Parts of Speech":"NOUN","Tamil Words":"uṇavu","Irula Words":"cooru, puṭṭu","Toda Words":"twi:r","Meaning":"Any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth"},
{"English Words":"For me","Parts of Speech":"","Tamil Words":"enakka:ka","Irula Words":"ena:","Toda Words":"","Meaning":""},
{"English Words":"For us","Parts of Speech":"","Tamil Words":"enakku","Irula Words":"enukku","Toda Words":"","Meaning":""},
{"English Words":"For you","Parts of Speech":"","Tamil Words":"unakka:ka","Irula Words":"ninukka:ka","Toda Words":"","Meaning":""},
{"English Words":"Forehead (n)","Parts of Speech":"NOUN","Tamil Words":"netti","Irula Words":"netti","Toda Words":"nity","Meaning":"The part of the face above the eyebrows"},
{"English Words":"Frecalmater (goat)","Parts of Speech":"","Tamil Words":"pulukkai","Irula Words":"pu:kku","Toda Words":"","Meaning":""},
{"English Words":"Frog (n)","Parts of Speech":"NOUN","Tamil Words":"tavaḷai","Irula Words":"kappe","Toda Words":"","Meaning":"A tailless amphibian with a short squat body, moist smooth skin, and very long hind legs for leaping"},
{"English Words":"From me","Parts of Speech":"","Tamil Words":"ennitamirunthu","Irula Words":"ettiruntu","Toda Words":"","Meaning":""},
{"English Words":"From us","Parts of Speech":"","Tamil Words":"enkalitamirunthu","Irula Words":"emitirunthu","Toda Words":"","Meaning":""},
{"English Words":"Front (n)","Parts of Speech":"NOUN","Tamil Words":"munna:l","Irula Words":"muntukku","Toda Words":"","Meaning":"The side or part of an object that presents itself to view or that is normally seen or used first; the most forward part of something"},
{"English Words":"Fruit (n)","Parts of Speech":"NOUN","Tamil Words":"paḻam","Irula Words":"pa:mu","Toda Words":"pum","Meaning":"the sweet and fleshy product of a tree or other plant that contains seed and can be eaten as food"},
{"English Words":"Full (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"muluvatum ","Irula Words":"muluca , muluca: ","Toda Words":"","Meaning":"Containing or holding as much or as many as possible; having no empty space"},
{"English Words":"Function (n)","Parts of Speech":"NOUN","Tamil Words":"tiruvila:","Irula Words":"trula:","Toda Words":"","Meaning":"An activity that is natural to or the purpose of a person or thing"},
{"English Words":"flower","Parts of Speech":"NOUN","Tamil Words":"malar","Irula Words":"","Toda Words":"pu:f","Meaning":"The seed-bearing part of a plant, consisting of reproductive organs (stamens and carpels) that are typically surrounded by a brightly coloured corolla (petals) and a green calyx (sepals)."},
{"English Words":"Floor","Parts of Speech":"NOUN","Tamil Words":"tarai","Irula Words":"","Toda Words":"kutte:r","Meaning":"The lower surface of a room, on which one may walk."},
{"English Words":"friend","Parts of Speech":"NOUN","Tamil Words":"naṇpaṉ","Irula Words":"","Toda Words":"ego:ṭ","Meaning":"A person with whom one has a bond of mutual affection."},
{"English Words":"flour","Parts of Speech":"NOUN","Tamil Words":"ma:vu","Irula Words":"","Toda Words":"iṭ","Meaning":"A powder obtained by grinding grain, typically wheat, and used to make bread, cakes, and pastry."},
{"English Words":"fifty","Parts of Speech":"NUMBER","Tamil Words":"aimpatu","Irula Words":"","Toda Words":"ebod","Meaning":"The number equivalent to the product of five and ten"},
{"English Words":"File","Parts of Speech":"NOUN","Tamil Words":"ko:ppu","Irula Words":"","Toda Words":"arm","Meaning":"A folder or box for holding loose papers together and in order for easy reference."},
{"English Words":"Fork used in digging","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"mul","Meaning":""},
{"English Words":"Face","Parts of Speech":"NOUN","Tamil Words":"mukam","Irula Words":"","Toda Words":"koṇmun","Meaning":"The front part of a person's head from the forehead to the chin, or the corresponding part in an animal."},
{"English Words":"Garden Lizard","Parts of Speech":"NOUN","Tamil Words":"pa:mparaṇai","Irula Words":"pa:mpuraNNe","Toda Words":"","Meaning":"A reptile that typically has a long body and tail, four legs, movable eyelids, and a rough, scaly, or spiny skin"},
{"English Words":"Get up","Parts of Speech":"VERB","Tamil Words":"eluntutta:","Irula Words":"e:ttutta:","Toda Words":"","Meaning":"Rise or cause to rise from bed after sleeping."},
{"English Words":"Getdown (v)","Parts of Speech":"VERB","Tamil Words":"irakkividu","Irula Words":"raikkidu","Toda Words":"","Meaning":"Phrasal verb of get"},
{"English Words":"Ghost (n)","Parts of Speech":"NOUN","Tamil Words":"pe;iy","Irula Words":"pe:yi","Toda Words":"","Meaning":"An apparition of a dead person which is believed to appear or become manifest to the living, typically as a nebulous image."},
{"English Words":"Giddiness (n)","Parts of Speech":"NOUN","Tamil Words":"mayakkam","Irula Words":"kkirukiruppe","Toda Words":"","Meaning":"A sensation of whirling and a tendency to fall or stagger; dizziness"},
{"English Words":"Girl in a grow","Parts of Speech":"","Tamil Words":"ku:ttattil oruthi","Irula Words":"ku:ttaparu","Toda Words":"","Meaning":""},
{"English Words":"Give (v)","Parts of Speech":"VERB","Tamil Words":"koṭu","Irula Words":"kodu, koduka:ru, tarukaaru","Toda Words":"","Meaning":"Freely transfer the possession of (something) to (someone)"},
{"English Words":"Given (what we) (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"koduttete","Irula Words":"kodutte","Toda Words":"","Meaning":"Specified or stated"},
{"English Words":"Go away","Parts of Speech":"","Tamil Words":"po:vidu","Irula Words":"po:yiru","Toda Words":"pi:x","Meaning":""},
{"English Words":"Goat (n)","Parts of Speech":"NOUN","Tamil Words":"veḷḷa:ṭu","Irula Words":"aaṭe","Toda Words":"e:d","Meaning":"A hardy domesticated ruminant mammal that has backward-curving horns and (in the male) a beard"},
{"English Words":"God (n)","Parts of Speech":"NOUN","Tamil Words":"Tēvaṉ, kaṭavuḷ","Irula Words":"veṭṭa ma:riyamman, patraka:li, veṭṭaka:ran, perumal, Raman, viiraka:liyatta, maariyatta","Toda Words":"so:my","Meaning":"The supreme being"},
{"English Words":"Gone (v)","Parts of Speech":"VERB","Tamil Words":"po:iyvatta:n","Irula Words":"po:itta:","Toda Words":"","Meaning":"No longer present; departed"},
{"English Words":"Grab (v)","Parts of Speech":"VERB","Tamil Words":"pari","Irula Words":"ra;kku","Toda Words":"","Meaning":"Grasp or seize suddenly and roughly"},
{"English Words":"Grandfather (n)","Parts of Speech":"NOUN","Tamil Words":"appa:viṇ appa:","Irula Words":"ta:tta:","Toda Words":"","Meaning":"The father of one's father or mother"},
{"English Words":"Grandmother (n)","Parts of Speech":"NOUN","Tamil Words":"appa:viṇ amma:","Irula Words":"appe appe","Toda Words":"","Meaning":"The mother of one's father or mother"},
{"English Words":"Grass (n)","Parts of Speech":"NOUN","Tamil Words":"pul","Irula Words":"pillu","Toda Words":"mi:c","Meaning":"Vegetation consisting of typically short plants with long, narrow leaves, growing wild or cultivated on lawns and pasture, and as a fodder crop"},
{"English Words":"Greens (n)","Parts of Speech":"NOUN","Tamil Words":"ke:rai ","Irula Words":"da:gu","Toda Words":"","Meaning":"Green vegetables"},
{"English Words":"Green leaf ","Parts of Speech":"","Tamil Words":"ki:rai","Irula Words":"daaku","Toda Words":"sup","Meaning":"A flattened structure of a higher plant, typically green and blade-like, that is attached to a stem directly or via a stalk. "},
{"English Words":"Grind (v)","Parts of Speech":"VERB","Tamil Words":"araittu, araiccu","Irula Words":"rettu, recci","Toda Words":"","Meaning":"Reduce (something) to small particles or powder by crushing it"},
{"English Words":"Ground (n)","Parts of Speech":"NOUN","Tamil Words":"tarai","Irula Words":"tare","Toda Words":"","Meaning":"The solid surface of the earth"},
{"English Words":"Good potatoes","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"nḷḷki:siye:","Meaning":""},
{"English Words":"Ghee","Parts of Speech":"NOUN","Tamil Words":"Ney","Irula Words":"","Toda Words":"heyyi:","Meaning":"Clarified butter made from the milk of a buffalo or cow, used in South Asian cooking."},
{"English Words":"Green","Parts of Speech":"ADJECTIVE","Tamil Words":"paccai","Irula Words":"","Toda Words":"lomodhi","Meaning":"The colour between blue and yellow in the spectrum; coloured like grass or emeralds."},
{"English Words":"grazing","Parts of Speech":"NOUN","Tamil Words":"mēyccal","Irula Words":"","Toda Words":"me:schch","Meaning":"Grassland suitable for pasturage"},
{"English Words":"Hair (n)","Parts of Speech":"NOUN","Tamil Words":"muṭi","Irula Words":"megaru, meguru, mudi ","Toda Words":"mi:r","Meaning":"Any of the fine thread-like strands growing from the skin of humans, mammals, and some other animals"},
{"English Words":"Hair bond","Parts of Speech":"","Tamil Words":"muṭi piṇaippu","Irula Words":"cede:, cëde: ","Toda Words":"","Meaning":""},
{"English Words":"Hairbin (n)","Parts of Speech":"","Tamil Words":"cadai","Irula Words":"cede, ce;de: ","Toda Words":"","Meaning":""},
{"English Words":"He is singing","Parts of Speech":"","Tamil Words":"padukira:l","Irula Words":"pa:duka","Toda Words":"","Meaning":""},
{"English Words":"He is taking","Parts of Speech":"","Tamil Words":"pe:cukira:n","Irula Words":"pecuka","Toda Words":"","Meaning":""},
{"English Words":"Head (n)","Parts of Speech":"NOUN","Tamil Words":"talai","Irula Words":"tola, tele, tele:","Toda Words":"mad","Meaning":"The upper part of the human body, or the front or upper part of the body of an animal, typically separated from the rest of the body by a neck, and containing the brain, mouth, and sense organs"},
{"English Words":"Headache (n)","Parts of Speech":"NOUN","Tamil Words":"talai vali","Irula Words":"televeṭṭu, cilecereṅku","Toda Words":"","Meaning":"A continuous pain in the head"},
{"English Words":"Heel (n)","Parts of Speech":"NOUN","Tamil Words":"kutika:l","Irula Words":"Kuka:l","Toda Words":"","Meaning":"The back part of the human foot below the ankle"},
{"English Words":"Hen (n)","Parts of Speech":"NOUN","Tamil Words":"ko:ḻi","Irula Words":"kooyi","Toda Words":"","Meaning":"A female bird, especially of a domestic fowl"},
{"English Words":"Here (adv)","Parts of Speech":"ADVERB","Tamil Words":"inku","Irula Words":"i:nku","Toda Words":"","Meaning":"In, at, or to this place or position"},
{"English Words":"Hide (v)","Parts of Speech":"VERB","Tamil Words":"maṟai","Irula Words":"morattiṭu","Toda Words":"","Meaning":"Put or keep out of sight"},
{"English Words":"Hill (n)","Parts of Speech":"NOUN","Tamil Words":"malai","Irula Words":"mele, me:le","Toda Words":"","Meaning":"A naturally raised area of land, not as high or craggy as a mountain"},
{"English Words":"Hold ","Parts of Speech":"VERB","Tamil Words":"piṭi","Irula Words":"kettita puruttukko: ","Toda Words":"","Meaning":"Grasp, carry, or support with one's arms or hands"},
{"English Words":"Home (n)","Parts of Speech":"NOUN","Tamil Words":"vacikkum ve:du ","Irula Words":"va:lha ke:re: ","Toda Words":"","Meaning":"The place where one lives permanently, especially as a member of a family or household"},
{"English Words":"Honey bee (n)","Parts of Speech":"NOUN","Tamil Words":"teṉi","Irula Words":"teenkuNNi","Toda Words":"to:n","Meaning":"A bee of a type that collects nectar and pollen, produces wax and honey, and lives in large communities; a hive bee"},
{"English Words":"Horn (n)","Parts of Speech":"NOUN","Tamil Words":"kompu","Irula Words":"kompu, kompe, kombu","Toda Words":"","Meaning":"A hard permanent outgrowth, often curved and pointed, found in pairs on the heads of cattle, sheep, goats, giraffes, etc. and consisting of a core of bone encased in keratinized skin"},
{"English Words":"House (n)","Parts of Speech":"NOUN","Tamil Words":"veedu","Irula Words":"ku:re","Toda Words":"a:s","Meaning":"A building for human habitation, especially one that consists of a ground floor and one or more upper storeys"},
{"English Words":"How big","Parts of Speech":"","Tamil Words":"evvalavu periya","Irula Words":"ebbella:","Toda Words":"","Meaning":""},
{"English Words":"Hug (v)","Parts of Speech":"VERB","Tamil Words":"kaṭṭikkoḷ","Irula Words":"tappipiṭi","Toda Words":"","Meaning":"Squeeze (someone) tightly in one's arms, typically to express affection"},
{"English Words":"Husband (n)","Parts of Speech":"NOUN","Tamil Words":"kaṇavan","Irula Words":"ba:va:, viiṭa:lu, etta viiṭulullavanga","Toda Words":"","Meaning":"A married man considered in relation to his spouse"},
{"English Words":"he buffalo","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"he:r","Meaning":""},
{"English Words":"how","Parts of Speech":"ADVERB","Tamil Words":"eppaṭi","Irula Words":"","Toda Words":"egis","Meaning":"In what way or manner; by what means."},
{"English Words":"hole","Parts of Speech":"NOUN","Tamil Words":"tuḷai","Irula Words":"","Toda Words":"a:ṟ","Meaning":"A hollow place in a solid body or surface."},
{"English Words":"half","Parts of Speech":"NOUN","Tamil Words":"arai","Irula Words":"","Toda Words":"ar","Meaning":"Either of two equal or corresponding parts into which something is or can be divided."},
{"English Words":"hot water","Parts of Speech":"","Tamil Words":"venni:r","Irula Words":"","Toda Words":"a:ni:r","Meaning":""},
{"English Words":"horn buffalo","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"kuorh","Meaning":""},
{"English Words":"Horse","Parts of Speech":"NOUN","Tamil Words":"kutirai","Irula Words":"","Toda Words":"ha:rh","Meaning":""},
{"English Words":"I","Parts of Speech":"PRONOUN","Tamil Words":"na:n","Irula Words":"na:nu","Toda Words":"","Meaning":"Used by a speaker to refer to himself or herself"},
{"English Words":"If (which day) ","Parts of Speech":"CONJUNCTION","Tamil Words":"endru","Irula Words":"endu","Toda Words":"","Meaning":"On the condition or supposition that; in the event that"},
{"English Words":"In a crowd","Parts of Speech":"","Tamil Words":"ku:ttama:ka","Irula Words":"ku:ttama:","Toda Words":"","Meaning":""},
{"English Words":"In here","Parts of Speech":"","Tamil Words":"irukkiran","Irula Words":"irukka:","Toda Words":"","Meaning":""},
{"English Words":"In presence","Parts of Speech":"","Tamil Words":"irukkumpo:tu, Irukkumpo:thu","Irula Words":"irukkapotu","Toda Words":"","Meaning":""},
{"English Words":"In thin","Parts of Speech":"","Tamil Words":"itil","Irula Words":"itli","Toda Words":"","Meaning":""},
{"English Words":"Insect","Parts of Speech":"NOUN","Tamil Words":"puci","Irula Words":"punci","Toda Words":"","Meaning":"A small arthropod animal that has six legs and generally one or two pairs of wings"},
{"English Words":"Instrument (n)","Parts of Speech":"NOUN","Tamil Words":"munvatti, hunting","Irula Words":"lo:gari, pa:ve","Toda Words":"","Meaning":"A tool or implement, especially one for precision work"},
{"English Words":"Intestine (n)","Parts of Speech":"NOUN","Tamil Words":"kuṭal","Irula Words":"koṭa:lu","Toda Words":"","Meaning":"The lower part of the alimentary canal from the end of the stomach to the anus"},
{"English Words":"Invite (v)","Parts of Speech":"VERB","Tamil Words":"alai, alaittu","Irula Words":"le, elattu","Toda Words":"","Meaning":"Make a polite, formal, or friendly request to (someone) to go somewhere or to do something"},
{"English Words":"Is their","Parts of Speech":"","Tamil Words":"","Irula Words":"kitakkau , kita:kku , kitakkutu","Toda Words":"","Meaning":""},
{"English Words":"Kartikai (tamil month) (n)","Parts of Speech":"NOUN","Tamil Words":"kartikai","Irula Words":"kattike","Toda Words":"","Meaning":"Name of the month in tamil"},
{"English Words":"Keep (v)","Parts of Speech":"VERB","Tamil Words":"vaittukkol","Irula Words":"vettukko: ","Toda Words":"","Meaning":"Have or retain possession of"},
{"English Words":"Kilintirukkirathu (tore) (v)","Parts of Speech":"NOUN","Tamil Words":"kiḻi","Irula Words":"kintu","Toda Words":"","Meaning":"Simple past tense of tear (Pull (something) apart or to pieces with force)"},
{"English Words":"Kill (v)","Parts of Speech":"VERB","Tamil Words":"kol ","Irula Words":"kollu, kellu, kettukko:, catturu, kenturu","Toda Words":"","Meaning":"Cause the death of (a person, animal, or other living thing)"},
{"English Words":"Kiss (v)","Parts of Speech":"VERB","Tamil Words":"muttam","Irula Words":"muttu","Toda Words":"","Meaning":"Touch or caress with the lips as a sign of love, sexual desire, or greeting"},
{"English Words":"Knee (n)","Parts of Speech":"NOUN","Tamil Words":"muṭṭi","Irula Words":"muli, muttu","Toda Words":"","Meaning":"The joint between the thigh and the lower leg in humans"},
{"English Words":"Known ","Parts of Speech":"ADJECTIVE","Tamil Words":"teriyum","Irula Words":"teriyu, teri;, teri ","Toda Words":"","Meaning":"Past participle of know (recognized, familiar, or within the scope of knowledge)"},
{"English Words":"Kitchen place","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"me:r kutte:r","Meaning":""},
{"English Words":"knowledge","Parts of Speech":"NOUN","Tamil Words":"aṟivu","Irula Words":"","Toda Words":"aṟyfu","Meaning":"Facts, information, and skills acquired through experience or education; the theoretical or practical understanding of a subject."},
{"English Words":"Knife","Parts of Speech":"NOUN","Tamil Words":"katti","Irula Words":"","Toda Words":"tu:vi","Meaning":""},
{"English Words":"Leaf (n)","Parts of Speech":"NOUN","Tamil Words":"ilai","Irula Words":"ele, cappattu","Toda Words":"esh","Meaning":"A flattened structure of a higher plant, typically green and blade-like, that is attached to a stem directly or via a stalk"},
{"English Words":"Leave/let (v)","Parts of Speech":"VERB","Tamil Words":"viṭṭu","Irula Words":"udu","Toda Words":"l;f","Meaning":"Go away from"},
{"English Words":"Leech (n)","Parts of Speech":"NOUN","Tamil Words":"aṭṭai pu:cci","Irula Words":"aṭṭe","Toda Words":"ibfuf","Meaning":"An aquatic or terrestrial annelid worm with suckers at both ends"},
{"English Words":"Leg (n)","Parts of Speech":"NOUN","Tamil Words":"ka:l","Irula Words":"kelu","Toda Words":"ko:l","Meaning":"Each of the limbs on which a person or animal walks and stands"},
{"English Words":"Lemon (n)","Parts of Speech":"NOUN","Tamil Words":"elumiccai","Irula Words":"elumicca","Toda Words":"u:smic","Meaning":"A pale yellow oval citrus fruit with thick skin and fragrant, acidic juice"},
{"English Words":"Leopard (n)","Parts of Speech":"NOUN","Tamil Words":"ciṟuttai","Irula Words":"ṭekkeṭa","Toda Words":"ki:rmi:n","Meaning":"A large solitary cat that has a fawn or brown coat with black spots, native to the forests of Africa and southern Asia"},
{"English Words":"Letters (n)","Parts of Speech":"NOUN","Tamil Words":"kaditamkal","Irula Words":"kaditanka","Toda Words":"","Meaning":"A written, typed, or printed communication, sent in an envelope by post or messenger"},
{"English Words":"Lip (n)","Parts of Speech":"NOUN","Tamil Words":"utatu","Irula Words":"mattu","Toda Words":"utir","Meaning":"Either of the two fleshy parts which form the upper and lower edges of the opening of the mouth"},
{"English Words":"Lock (n)","Parts of Speech":"NOUN","Tamil Words":"pu:ṭu","Irula Words":"torappu","Toda Words":"kozpini","Meaning":"A mechanism for keeping a door, window, lid, or container fastened, typically operated by a key"},
{"English Words":"Long (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"ne:lama:na","Irula Words":"oc:kama:na, bella:, ne:lama:, uttama:na, me:lama:na","Toda Words":"","Meaning":"Measuring a great distance from end to end"},
{"English Words":"Lost ","Parts of Speech":"VERB","Tamil Words":"tolaintuvittai","Irula Words":"teluntutta","Toda Words":"","Meaning":"Past and past participle of lose (unable to find one's way; not knowing one's whereabouts)"},
{"English Words":"Love (n)","Parts of Speech":"NOUN","Tamil Words":"aṉpu","Irula Words":"pa:cam","Toda Words":"kaf","Meaning":"A strong feeling of affection"},
{"English Words":"leaving to dry","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"tu:rvoḍuttiye","Meaning":""},
{"English Words":"ladder","Parts of Speech":"NOUN","Tamil Words":"e:ṇi","Irula Words":"","Toda Words":"e:ṇy","Meaning":"A piece of equipment consisting of a series of bars or steps between two upright lengths of wood, metal, or rope, used for climbing up or down something."},
{"English Words":"Line closed(paar muduthal)","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"po:rmustiye:","Meaning":""},
{"English Words":"lamp","Parts of Speech":"NOUN","Tamil Words":"viḷakku","Irula Words":"","Toda Words":"puḻkki","Meaning":""},
{"English Words":"Madeup of wood","Parts of Speech":"","Tamil Words":"kucciyil piṉṉappaṭṭa vlai","Irula Words":"peṭulu","Toda Words":"","Meaning":""},
{"English Words":"Makaal cousin","Parts of Speech":"","Tamil Words":"periayppa: ","Irula Words":"entenga","Toda Words":"","Meaning":""},
{"English Words":"Mango Tree","Parts of Speech":"","Tamil Words":"ma: maram","Irula Words":"maṅkaay maram","Toda Words":"","Meaning":"The evergreen tropical Indian tree which bears the mango"},
{"English Words":"Marriage (n)","Parts of Speech":"NOUN","Tamil Words":"kalya:ṇam","Irula Words":"ta:likaṭṭu","Toda Words":"","Meaning":"The legally or formally recognized union of two people as partners in a personal relationship "},
{"English Words":"Me (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"ennai","Irula Words":"enne:","Toda Words":"","Meaning":"Used by a speaker to refer to himself or herself as the object of a verb or preposition"},
{"English Words":"Measure (v)","Parts of Speech":"VERB","Tamil Words":"mattam, alantukkko","Irula Words":"tu:kkuppa:di, lentukko:","Toda Words":"ačok","Meaning":"Ascertain the size, amount, or degree of (something) by using an instrument or device marked in standard units"},
{"English Words":"Mid-night","Parts of Speech":"","Tamil Words":"naṭu iravu","Irula Words":"ca:mam","Toda Words":"","Meaning":""},
{"English Words":"Milk (n)","Parts of Speech":"NOUN","Tamil Words":"pa:l","Irula Words":"ba:llu, bellu","Toda Words":"","Meaning":"An opaque white fluid rich in fat and protein, secreted by female mammals for the nourishment of their young"},
{"English Words":"Mine (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"ennutaiya, ennatu, ennutaiyathu","Irula Words":"ettutaiya, ettu, ettuta:ya","Toda Words":"","Meaning":"Used to refer to a thing or things belonging to or associated with the speaker"},
{"English Words":"Missing (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"ka:navillai","Irula Words":"ka:na:","Toda Words":"","Meaning":"(of a thing) not able to be found because it is not in its expected place"},
{"English Words":"Mist (n)","Parts of Speech":"NOUN","Tamil Words":"me:gam ","Irula Words":"mega;, manju ","Toda Words":"","Meaning":"A cloud of tiny water droplets suspended in the atmosphere at or near the earth's surface that limits visibility"},
{"English Words":"Monkey (n)","Parts of Speech":"NOUN","Tamil Words":"kuraṅku","Irula Words":"koraaṅku","Toda Words":"","Meaning":"A small to medium-sized primate that typically has a long tail, most kinds of which live in trees in tropical countries"},
{"English Words":"Month (n)","Parts of Speech":"NOUN","Tamil Words":"ma:tam","Irula Words":"appaaci","Toda Words":"","Meaning":"Each of the twelve named periods into which a year is divided"},
{"English Words":"Moon (n)","Parts of Speech":"NOUN","Tamil Words":"nila: ","Irula Words":"nela:vu, to:vi, to:vi, nela:vu ","Toda Words":"tigil","Meaning":"The natural satellite of the earth, visible (chiefly at night) by reflected light from the sun"},
{"English Words":"Morning (n)","Parts of Speech":"NOUN","Tamil Words":"ka:lai","Irula Words":"ka:lame","Toda Words":"I:sy","Meaning":"The period of time between midnight and noon, especially from sunrise to noon"},
{"English Words":"Mosquito (n)","Parts of Speech":"NOUN","Tamil Words":"kocu","Irula Words":"collu","Toda Words":"erb","Meaning":"A slender long-legged fly with aquatic larvae"},
{"English Words":"Mother (n)","Parts of Speech":"NOUN","Tamil Words":"amma:, ta:y            ","Irula Words":"avga , amma: , akkalu, avva:          ","Toda Words":"tyafa:","Meaning":"A woman in relation to her child or children"},
{"English Words":"Mother-in-law (n)","Parts of Speech":"NOUN","Tamil Words":"maṉaiviyiṉ amma:/ kaṇavaṉiṉ amma:","Irula Words":"ma:mi","Toda Words":"","Meaning":"The mother of one's husband or wife"},
{"English Words":"Mouse (n)","Parts of Speech":"NOUN","Tamil Words":"eli","Irula Words":"cuṇṭeli, perucali","Toda Words":"isy","Meaning":"Any small mammal similar to a mouse, such as a shrew or vole"},
{"English Words":"Muscle (n)","Parts of Speech":"NOUN","Tamil Words":"tcai","Irula Words":"cete","Toda Words":"pi:t","Meaning":"a band or bundle of fibrous tissue in a Human or animal body that has the ability to contract, producing movement in or maintaining the position of parts of the body"},
{"English Words":"Myna (n)","Parts of Speech":"NOUN","Tamil Words":"maiṉa:","Irula Words":"maiṉa:kkuruvi","Toda Words":"","Meaning":"An Asian and Australasian starling that typically has dark plumage, gregarious behaviour, and a loud call"},
{"English Words":"meaning","Parts of Speech":"NOUN","Tamil Words":"arttam","Irula Words":"","Toda Words":"artm","Meaning":"What is meant by a word, text, concept, or action."},
{"English Words":"mountain","Parts of Speech":"NOUN","Tamil Words":"malai","Irula Words":"","Toda Words":"e:tir","Meaning":"A large natural elevation of the earth's surface rising abruptly from the surrounding level; a large steep hill."},
{"English Words":"mirror","Parts of Speech":"NOUN","Tamil Words":"kaṇṇa:ṭi","Irula Words":"","Toda Words":"ark","Meaning":"A surface, typically of glass coated with a metal amalgam, which reflects a clear image."},
{"English Words":"milking vessel","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"ko:nipiṇṇ","Meaning":""},
{"English Words":"","Parts of Speech":"","Tamil Words":"Man katrathu","Irula Words":"","Toda Words":"mo:nkoḍuttiye:","Meaning":""},
{"English Words":"Nake leash","Parts of Speech":"","Tamil Words":"kattuva:ru","Irula Words":"kettuva:ru","Toda Words":"","Meaning":""},
{"English Words":"Name (n)","Parts of Speech":"NOUN","Tamil Words":"pe:r, pe:ru","Irula Words":"pe:ru, beru","Toda Words":"","Meaning":"A word or set of words by which a person or thing is known, addressed, or referred to"},
{"English Words":"Name of birds","Parts of Speech":"","Tamil Words":"kuruvi ","Irula Words":"keruvi, kirivi","Toda Words":"","Meaning":""},
{"English Words":"Name of festival","Parts of Speech":"","Tamil Words":"taippongal","Irula Words":"teponga","Toda Words":"","Meaning":""},
{"English Words":"Name of tuber","Parts of Speech":"","Tamil Words":"","Irula Words":"riya:s","Toda Words":"","Meaning":""},
{"English Words":"Navel (n)","Parts of Speech":"NOUN","Tamil Words":"toppuḷ","Irula Words":"pokkuṭṭi","Toda Words":"piku:","Meaning":"A rounded knotty depression in the centre of a person's belly caused by the detachment of the umbilical cord after birth; the umbilicus"},
{"English Words":"Neck (n)","Parts of Speech":"NOUN","Tamil Words":"kalutthu, kaluttu ","Irula Words":"kattu, kettu, ka:ttu, kkettu","Toda Words":"mir","Meaning":"The part of a person's or animal's body connecting the head to the rest of the body"},
{"English Words":"Nest (n)","Parts of Speech":"NOUN","Tamil Words":"ku:ṭu","Irula Words":"kku:du","Toda Words":"ku:d","Meaning":"A structure or place made or chosen by a bird for laying eggs and sheltering its young"},
{"English Words":"Net","Parts of Speech":"NOUN","Tamil Words":"valai","Irula Words":"vale;","Toda Words":"pal","Meaning":"An open fabric of string or rope or wire woven together at regular intervals"},
{"English Words":"New (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"putiya ","Irula Words":"putuvu, putucu, putuca","Toda Words":"pun","Meaning":"Produced, introduced, or discovered recently or now for the first time; not existing before"},
{"English Words":"Night (n)","Parts of Speech":"NOUN","Tamil Words":"iravu","Irula Words":"ra:vu, andi, ra:vu, rettu, iruṭṭukaṭṭutu","Toda Words":"i:t","Meaning":"The period from sunset to sunrise in each twenty-four hours"},
{"English Words":"Not mine","Parts of Speech":"","Tamil Words":"ennatillai","Irula Words":"ettella","Toda Words":"","Meaning":""},
{"English Words":"Not with staying","Parts of Speech":"","Tamil Words":"iruntalum ku:ta","Irula Words":"iruppatu ku:ta","Toda Words":"","Meaning":""},
{"English Words":"Now (adv)","Parts of Speech":"ADVERB","Tamil Words":"ippo:thu, ippoluthu, tarpoluthu","Irula Words":"ippena:kku, ippete:, ippotu, tarpo:thu","Toda Words":"i:ṇy","Meaning":"At the present time or moment"},
{"English Words":"Needle","Parts of Speech":"NOUN","Tamil Words":"u:ci","Irula Words":"","Toda Words":"ibbi","Meaning":""},
{"English Words":"Observe (v)","Parts of Speech":"VERB","Tamil Words":"kavaṉikkavum","Irula Words":"kevani","Toda Words":"","Meaning":"Notice or perceive (something) and register it as being significant"},
{"English Words":"Old lady (n)","Parts of Speech":"NOUN","Tamil Words":"vayata:ṉa peṇmaṇi","Irula Words":"bellava","Toda Words":"","Meaning":"An elderly woman"},
{"English Words":"Old man (n)","Parts of Speech":"NOUN","Tamil Words":"vayata:navar","Irula Words":"bellavar","Toda Words":"","Meaning":"An elderly male person"},
{"English Words":"Old Man/ Old Woman (n)","Parts of Speech":"","Tamil Words":"vayata:ṉavar","Irula Words":"pellavar","Toda Words":"","Meaning":"An elderly male/ female person"},
{"English Words":"On me","Parts of Speech":"","Tamil Words":"enme:le:","Irula Words":"ettumele","Toda Words":"","Meaning":""},
{"English Words":"Onion (n)","Parts of Speech":"NOUN","Tamil Words":"ciṉṉa veṅka:yam, periya veṅka:yam","Irula Words":"cinna veṅkaayi, pella veṅkaayi","Toda Words":"","Meaning":"A swollen edible bulb used as a vegetable, having a pungent taste and smell and composed of several concentric layers"},
{"English Words":"Only now","Parts of Speech":"","Tamil Words":"ippolututa:n","Irula Words":"ippo:tuta;","Toda Words":"","Meaning":""},
{"English Words":"Open (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"tiṟa","Irula Words":"toRa","Toda Words":"","Meaning":"Allowing access, passage, or a view through an empty space; not closed or blocked"},
{"English Words":"Orange Flower","Parts of Speech":"","Tamil Words":"a:rañcu pu:","Irula Words":"kaṇaka:m pu:","Toda Words":"","Meaning":""},
{"English Words":"Our (determiner)","Parts of Speech":"DETERMINER","Tamil Words":"eṅkaḷ","Irula Words":"emuthutaya","Toda Words":"","Meaning":"Belonging to or associated with the speaker and one or more other people previously mentioned or easily identified"},
{"English Words":"Ours (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"enkalutayatu, nammutaiyatu, nammutaya","Irula Words":"emuthutayatu, namututayatu, namattutaya","Toda Words":"","Meaning":"Used to refer to a thing or things belonging to or associated with the speaker and one or more other people previously mentioned or easily identified"},
{"English Words":"Ours only","Parts of Speech":"","Tamil Words":"enkalutayathe:","Irula Words":"etto:","Toda Words":"","Meaning":""},
{"English Words":"Owl (n)","Parts of Speech":"NOUN","Tamil Words":"a:ntai","Irula Words":"kumeepa:ru","Toda Words":"","Meaning":"A nocturnal bird of prey with large eyes, a facial disc, a hooked beak, and typically a loud hooting call"},
{"English Words":"Ox (n)","Parts of Speech":"NOUN","Tamil Words":"ka:ḷai","Irula Words":"erutu","Toda Words":"","Meaning":"A domesticated bovine animal kept for milk or meat; a cow or bull."},
{"English Words":"oil","Parts of Speech":"NOUN","Tamil Words":"eṇṇai","Irula Words":"","Toda Words":"eṇo:y","Meaning":"a viscous liquid derived from petroleum, especially for use as a fuel or lubricant."},
{"English Words":"Pain (n)","Parts of Speech":"NOUN","Tamil Words":"vali, vayṟu vali","Irula Words":"veli, vekuruveli","Toda Words":"","Meaning":"Highly unpleasant physical sensation caused by illness or injury"},
{"English Words":"Past (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"p o;na ","Irula Words":"pe:na","Toda Words":"","Meaning":"Gone by in time and no longer existing"},
{"English Words":"Periyamma","Parts of Speech":"","Tamil Words":"periyappa","Irula Words":"periyamme, periappe, periamma","Toda Words":"","Meaning":""},
{"English Words":"Picture (n)","Parts of Speech":"NOUN","Tamil Words":"paṭam","Irula Words":"pata:, pata:ru","Toda Words":"","Meaning":"A painting or drawing"},
{"English Words":"Pig (n)","Parts of Speech":"NOUN","Tamil Words":"paṉṟi","Irula Words":"penti","Toda Words":"pody","Meaning":"An omnivorous domesticated hoofed mammal with sparse bristly hair and a flat snout for rooting in the soil, kept for its meat"},
{"English Words":"Pillow (n)","Parts of Speech":"NOUN","Tamil Words":"talayanai","Irula Words":"te:muttai","Toda Words":"","Meaning":"A rectangular cloth bag stuffed with feathers or other soft materials, used to support the head when lying or sleeping"},
{"English Words":"Pit (n)","Parts of Speech":"NOUN","Tamil Words":"kuli ","Irula Words":"kuyi","Toda Words":"","Meaning":"A large hole in the ground"},
{"English Words":"Porcupine (n)","Parts of Speech":"NOUN","Tamil Words":"muḷḷam paṉṟi","Irula Words":"muḻḻam penti","Toda Words":"","Meaning":"A large rodent with defensive spines or quills on the body and tail"},
{"English Words":"Pot (n)","Parts of Speech":"NOUN","Tamil Words":"kuṭam","Irula Words":"ca:lu","Toda Words":"","Meaning":"A rounded or cylindrical container, typically of metal, used for cooking"},
{"English Words":"Pray (v)","Parts of Speech":"VERB","Tamil Words":"kumpiṭu","Irula Words":"kumpuṭu","Toda Words":"","Meaning":"Wish or hope strongly for a particular outcome or situation"},
{"English Words":"Prestle","Parts of Speech":"","Tamil Words":"ulakkai","Irula Words":"lakke","Toda Words":"","Meaning":""},
{"English Words":"Prevent (v)","Parts of Speech":"VERB","Tamil Words":"taduttuvidu","Irula Words":"dettuvituru","Toda Words":"","Meaning":"Keep (something) from happening"},
{"English Words":"Pumpkin (n)","Parts of Speech":"NOUN","Tamil Words":"pu:caṇikka:y","Irula Words":"cakkarak kaayi","Toda Words":"","Meaning":"A large rounded orange-yellow fruit with a thick rind, the flesh of which can be used in sweet or savoury dishes"},
{"English Words":"Put (v)","Parts of Speech":"VERB","Tamil Words":"vai","Irula Words":"ituve","Toda Words":"i:t","Meaning":"Move to or place in a particular position"},
{"English Words":"palace","Parts of Speech":"NOUN","Tamil Words":"araṇmaṉai","Irula Words":"","Toda Words":"arman","Meaning":"A large and impressive building forming the official residence of a ruler, pope, archbishop, etc."},
{"English Words":"place","Parts of Speech":"NOUN","Tamil Words":"Iṭam","Irula Words":"","Toda Words":"iṟṇ","Meaning":"A particular position, point, or area in space; a location."},
{"English Words":"poor","Parts of Speech":"ADJECTIVE","Tamil Words":"e:ḻai","Irula Words":"","Toda Words":"e:ḷy","Meaning":"Lacking sufficient money to live at a standard considered comfortable or normal in a society."},
{"English Words":"plank","Parts of Speech":"NOUN","Tamil Words":"","Irula Words":"","Toda Words":"exe:ly","Meaning":"A long, thin, flat piece of timber, used especially in building and flooring."},
{"English Words":"power","Parts of Speech":"NOUN","Tamil Words":"cakti","Irula Words":"","Toda Words":"atixo:ṟm","Meaning":"The ability or capacity to do something or act in a particular way."},
{"English Words":"Potato","Parts of Speech":"NOUN","Tamil Words":"uruḷaikkiḻaṅku","Irula Words":"","Toda Words":"ki:s","Meaning":"A starchy plant tuber which is one of the most important food crops, cooked and eaten as a vegetable."},
{"English Words":"Question (n)","Parts of Speech":"NOUN","Tamil Words":"ke:lvi","Irula Words":"ke:vi","Toda Words":"","Meaning":"A doubt about the truth or validity of something"},
{"English Words":"Rabbit (n)","Parts of Speech":"NOUN","Tamil Words":"muyal","Irula Words":"mecalu","Toda Words":"","Meaning":"A gregarious burrowing plant-eating mammal, with long ears, long hind legs, and a short tail"},
{"English Words":"Radish (n)","Parts of Speech":"NOUN","Tamil Words":"muḷḷaṅki","Irula Words":"muḷḷaṅki","Toda Words":"","Meaning":"A swollen pungent-tasting edible root, especially a variety which is small, spherical, and red, and eaten raw with salad"},
{"English Words":"Rain (n)","Parts of Speech":"NOUN","Tamil Words":"malai","Irula Words":"me:, mel,mile , mele, me","Toda Words":"maw","Meaning":"The condensed moisture of the atmosphere falling visibly in separate drops"},
{"English Words":"Red (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"cikappu","Irula Words":"ceka:ppu, ceva:pu","Toda Words":"po:gh","Meaning":"Red colour or pigment"},
{"English Words":"Return (v)","Parts of Speech":"VERB","Tamil Words":"truppita:","Irula Words":"titta: ","Toda Words":"","Meaning":"Come or go back to a place or person"},
{"English Words":"Rool","Parts of Speech":"","Tamil Words":"uruttu","Irula Words":"ruttu","Toda Words":"","Meaning":""},
{"English Words":"Root (n)","Parts of Speech":"NOUN","Tamil Words":"ve:r","Irula Words":"ve:ru","Toda Words":"","Meaning":"The part of a plant which attaches it to the ground or to a support, typically underground, conveying water and nourishment to the rest of the plant via numerous branches and fibres"},
{"English Words":"Round (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"vattam ","Irula Words":"vatta: , vatte;","Toda Words":"","Meaning":"Shaped like a circle or cylinder"},
{"English Words":"Run (v)","Parts of Speech":"VERB","Tamil Words":"o:ṭu","Irula Words":"ooṭu","Toda Words":"o:t","Meaning":"Move at a speed faster than a walk, never having both or all the feet on the ground at the same time"},
{"English Words":"rotten potatoes","Parts of Speech":"ADJECTIVE","Tamil Words":"aḻukiya uruḷaikkiḻaṅku","Irula Words":"","Toda Words":"nu:vkissiye","Meaning":"Potatoes are in decay state."},
{"English Words":"rat","Parts of Speech":"NOUN","Tamil Words":"eli","Irula Words":"","Toda Words":"isy","Meaning":"A rodent that resembles a large mouse, typically having a pointed snout and a long tail. "},
{"English Words":"Rainy season","Parts of Speech":"","Tamil Words":"maḻaikka:lam","Irula Words":"","Toda Words":"e:ṇy","Meaning":""},
{"English Words":"Roof","Parts of Speech":"NOUN","Tamil Words":"Ku:rai","Irula Words":"","Toda Words":"pari","Meaning":"The structure forming the upper covering of a building or vehicle."},
{"English Words":"rice","Parts of Speech":"NOUN","Tamil Words":"arici","Irula Words":"","Toda Words":"asky","Meaning":"A swamp grass which is widely cultivated as a source of food, especially in Asia."},
{"English Words":"Saliva (n)","Parts of Speech":"NOUN","Tamil Words":"eccil","Irula Words":"ookelu","Toda Words":"","Meaning":"Watery liquid secreted into the mouth by glands, providing lubrication for chewing and swallowing, and aiding digestion"},
{"English Words":"Scorpion (n)","Parts of Speech":"NOUN","Tamil Words":"te:il ","Irula Words":"te:lu","Toda Words":"","Meaning":"A terrestrial arachnid which has lobster-like pincers and a poisonous sting at the end of its jointed tail, which it can hold curved over its back"},
{"English Words":"See (v)","Parts of Speech":"VERB","Tamil Words":"pa:ru","Irula Words":"peru","Toda Words":"","Meaning":"Perceive with the eyes; discern visually"},
{"English Words":"Seed (n)","Parts of Speech":"NOUN","Tamil Words":"vitai","Irula Words":"vetee","Toda Words":"","Meaning":"The unit of reproduction of a flowering plant, capable of developing into another such plant"},
{"English Words":"Seven","Parts of Speech":"NUMBER","Tamil Words":"e:lu","Irula Words":"e:le","Toda Words":"","Meaning":"Equivalent to the sum of three and four; one more than six, or three less than ten; 7."},
{"English Words":"Seventh standard","Parts of Speech":"","Tamil Words":"ela:vakuppu","Irula Words":"e:lavu","Toda Words":"","Meaning":""},
{"English Words":"Shall i sit","Parts of Speech":"","Tamil Words":"utka:rala:ma;","Irula Words":"Kukkattuma:","Toda Words":"","Meaning":""},
{"English Words":"Sharp (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"vall","Irula Words":"ve:lu, va:lu ","Toda Words":"","Meaning":"(of an object) having an edge or point that is able to cut or pierce something"},
{"English Words":"She is gone","Parts of Speech":"","Tamil Words":"po:iyvitta:l ","Irula Words":"po:iyta","Toda Words":"","Meaning":""},
{"English Words":"Sing (v)","Parts of Speech":"VERB","Tamil Words":"paṭu","Irula Words":"pa:ṭu","Toda Words":"","Meaning":"Make musical sounds with the voice, especially words with a set tune"},
{"English Words":"Sister-in-law (n)","Parts of Speech":"NOUN","Tamil Words":"aṇṇi","Irula Words":"nañkiya","Toda Words":"","Meaning":"The sister of one's wife or husband"},
{"English Words":"Sit down (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"uṭka:ru","Irula Words":"kukku","Toda Words":"","Meaning":"A period of sitting down; a short rest"},
{"English Words":"Skeleton (n)","Parts of Speech":"NOUN","Tamil Words":"elumbukku:du","Irula Words":"elumbuudu","Toda Words":"","Meaning":"An internal or external framework of bone, cartilage, or other rigid material supporting or containing the body of an animal or plant"},
{"English Words":"Skin (n)","Parts of Speech":"NOUN","Tamil Words":"to:lu","Irula Words":"teelu, to:il","Toda Words":"tu:erh","Meaning":"The thin layer of tissue forming the natural outer covering of the body of a person or animal"},
{"English Words":"Sleep (n)","Parts of Speech":"NOUN","Tamil Words":"uranku, tu:ṅku","Irula Words":"ranku, rongu, ra:nku, roṅku","Toda Words":"","Meaning":"A condition of body and mind which typically recurs for several hours every night, in which the nervous system is inactive, the eyes closed, the postural muscles relaxed, and consciousness practically suspended"},
{"English Words":"Sleeping (v)","Parts of Speech":"VERB","Tamil Words":"urankukira:r","Irula Words":"ronkuka:ru","Toda Words":"","Meaning":"Gerund or present participle: sleeping"},
{"English Words":"Small (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"cinnatu","Irula Words":"cinna , cinna:tu","Toda Words":"","Meaning":"Of a size that is less than normal or usual"},
{"English Words":"Small mother","Parts of Speech":"","Tamil Words":"cinnamma:","Irula Words":"cinema:, cinnamma, a:cci","Toda Words":"","Meaning":""},
{"English Words":"Smell (n)","Parts of Speech":"NOUN","Tamil Words":"va:caṉai","Irula Words":"maṉam","Toda Words":"","Meaning":"The faculty or power of perceiving odours or scents by means of the organs in the nose"},
{"English Words":"Smoke (n)","Parts of Speech":"NOUN","Tamil Words":"pugai ","Irula Words":"poge, poke:","Toda Words":"","Meaning":"A visible suspension of carbon or other particles in air, typically one emitted from a burning substance"},
{"English Words":"Snail (n)","Parts of Speech":"NOUN","Tamil Words":"nattai","Irula Words":"natte","Toda Words":"","Meaning":"A mollusc with a single spiral shell into which the whole body can be withdrawn"},
{"English Words":"Sneeze (v)","Parts of Speech":"VERB","Tamil Words":"tummal","Irula Words":"tumma","Toda Words":"","Meaning":"Make a sudden involuntary expulsion of air from the nose and mouth due to irritation of one's nostrils"},
{"English Words":"Sorrow (n)","Parts of Speech":"NOUN","Tamil Words":"co:kam","Irula Words":"vicuṉam","Toda Words":"tukm","Meaning":"A feeling of deep distress caused by loss, disappointment, or other misfortune suffered by oneself or others"},
{"English Words":"Spider (n)","Parts of Speech":"NOUN","Tamil Words":"eṭṭukka:l pu:cci","Irula Words":"pakku","Toda Words":"","Meaning":"An eight-legged predatory arachnid with an unsegmented body consisting of a fused head and thorax and a rounded abdomen"},
{"English Words":"Spoke (v)","Parts of Speech":"VERB","Tamil Words":"pé:cina:n","Irula Words":"pe:cana","Toda Words":"","Meaning":"Say something in order to convey information or to express a feeling"},
{"English Words":"Star (n)","Parts of Speech":"NOUN","Tamil Words":"natcattiram ","Irula Words":"moonu, natcatra:, natcattre , natcatti","Toda Words":"etukadci","Meaning":"A fixed luminous point in the night sky which is a large, remote incandescent body like the sun"},
{"English Words":"Stench (n)","Parts of Speech":"NOUN","Tamil Words":"na:ṟṟam, va:caṉai","Irula Words":"nattam","Toda Words":"","Meaning":"A strong and very unpleasant smell"},
{"English Words":"Stomach (n)","Parts of Speech":"NOUN","Tamil Words":"vayṟu","Irula Words":"vekuru","Toda Words":"pi:er","Meaning":"An appetite for food or drink"},
{"English Words":"Stone (n)","Parts of Speech":"NOUN","Tamil Words":"kal ","Irula Words":"ka;llu, ka:lu ","Toda Words":"kas","Meaning":"Hard solid non-metallic mineral matter of which rock is made, especially as a building material"},
{"English Words":"Stop (v)","Parts of Speech":"VERB","Tamil Words":"nil ","Irula Words":"nille, nattukko, nillu","Toda Words":"","Meaning":"(of an event, action, or process) come to an end; cease to happen"},
{"English Words":"Strong (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"uruti","Irula Words":"temper","Toda Words":"","Meaning":"Having the power to move heavy weights or perform other physically demanding tasks"},
{"English Words":"Strong various","Parts of Speech":"","Tamil Words":"","Irula Words":"bala","Toda Words":"","Meaning":""},
{"English Words":"Sun (n)","Parts of Speech":"NOUN","Tamil Words":"cu:riyan ","Irula Words":"potu, su:riya:, cu:riya, cu:riyai","Toda Words":"","Meaning":"The star round which the earth orbits"},
{"English Words":"Swallow (v)","Parts of Speech":"VERB","Tamil Words":"vilunku","Irula Words":"u:nku","Toda Words":"nug","Meaning":"Cause or allow (something, especially food or drink) to pass down the throat"},
{"English Words":"Sweat (n)","Parts of Speech":"NOUN","Tamil Words":"viyarvai","Irula Words":"veerve","Toda Words":"","Meaning":"Moisture exuded through the pores of the skin, typically in profuse quantities as a reaction to heat, physical exertion, fever, or fear"},
{"English Words":"Sweep (v)","Parts of Speech":"VERB","Tamil Words":"ku:ṭu","Irula Words":"oṭukku","Toda Words":"","Meaning":"Clean (an area) by brushing away dirt or litter"},
{"English Words":"Swim (v)","Parts of Speech":"VERB","Tamil Words":"ne:ntu","Irula Words":"mi:tta, ni:ttu ","Toda Words":"ni:dy","Meaning":"Propel the body through water by using the limbs, or (in the case of a fish or other aquatic animal) by using fins, tail, or other bodily movement"},
{"English Words":"shephard","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"erhnoḍthohiye:","Meaning":""},
{"English Words":"spear","Parts of Speech":"NOUN","Tamil Words":"i:ṭṭi","Irula Words":"","Toda Words":"i:ty","Meaning":"A weapon with a pointed tip, typically of steel, and a long shaft, used for thrusting or throwing."},
{"English Words":"somehow","Parts of Speech":"ADVERB","Tamil Words":"eppaṭiyo:","Irula Words":"","Toda Words":"egisem","Meaning":"in some way; by some means."},
{"English Words":"second","Parts of Speech":"Number","Tamil Words":"iraṇṭa:vatu","Irula Words":"","Toda Words":"e:ḍa:fio","Meaning":"Constituting number two in a sequence; coming after the first in time or order; 2nd."},
{"English Words":"squirrel","Parts of Speech":"NOUN","Tamil Words":"aṇil","Irula Words":"","Toda Words":"aṇil","Meaning":"An agile tree-dwelling rodent with a bushy tail, typically feeding on nuts and seeds."},
{"English Words":"surprise","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"a:sirym","Meaning":""},
{"English Words":"snot","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"i:ṇm","Meaning":""},
{"English Words":"sorrow","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aṟkil","Meaning":""},
{"English Words":"sixty","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aṟoo","Meaning":""},
{"English Words":"small potatoes","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"karki:siye:","Meaning":""},
{"English Words":"slave","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aḍimy","Meaning":""},
{"English Words":"straight","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"etir","Meaning":""},
{"English Words":"star","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"etukaḍci","Meaning":""},
{"English Words":"stable","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"tivo:rh","Meaning":""},
{"English Words":"Spade","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"keku:ṭe","Meaning":""},
{"English Words":"Shawl (Traditional dress toda)","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"pu:ttukuhi","Meaning":""},
{"English Words":"Tail (n)","Parts of Speech":"NOUN","Tamil Words":"va:l","Irula Words":"vvelu","Toda Words":"","Meaning":"The hindmost part of an animal"},
{"English Words":"Tear (v)","Parts of Speech":"VERB","Tamil Words":"kiḻi","Irula Words":"kiittiru","Toda Words":"","Meaning":"Pull (something) apart or to pieces with force"},
{"English Words":"Teeth (n)","Parts of Speech":"NOUN","Tamil Words":"pal","Irula Words":"pellu","Toda Words":"parh","Meaning":"Plural form of tooth (each of a set of hard, bony enamel-coated structures in the jaws of most vertebrates, used for biting and chewing)"},
{"English Words":"Tell (v)","Parts of Speech":"VERB","Tamil Words":"collu","Irula Words":"kellu","Toda Words":"","Meaning":"Communicate information to someone in spoken or written words"},
{"English Words":"Termite (n)","Parts of Speech":"NOUN","Tamil Words":"karaya:ṇ","Irula Words":"pevelu","Toda Words":"","Meaning":"A small, pale soft-bodied insect that lives in large colonies with several different castes, typically within a mound of cemented earth"},
{"English Words":"They told come","Parts of Speech":"","Tamil Words":"varuvata:ka","Irula Words":"varuge:ntu","Toda Words":"","Meaning":""},
{"English Words":"Thigh (n)","Parts of Speech":"NOUN","Tamil Words":"to:ṭai","Irula Words":"toṭe","Toda Words":"","Meaning":"The part of the human leg between the hip and the knee"},
{"English Words":"Think (v)","Parts of Speech":"VERB","Tamil Words":"ninai","Irula Words":"nenai","Toda Words":"","Meaning":"Have a particular belief or idea"},
{"English Words":"Thirteen","Parts of Speech":"","Tamil Words":"pathimu:nru","Irula Words":"pathimo:nu","Toda Words":"","Meaning":"Number 13"},
{"English Words":"This (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"itu","Irula Words":"iti, icca ","Toda Words":"","Meaning":"Used to identify a specific person or thing close at hand or being indicated or experienced"},
{"English Words":"This box","Parts of Speech":"","Tamil Words":"ippottiyai","Irula Words":"ippottiye:","Toda Words":"","Meaning":""},
{"English Words":"This house","Parts of Speech":"","Tamil Words":"intha v:du","Irula Words":"ivv:du","Toda Words":"a:s","Meaning":""},
{"English Words":"Thorn (n)","Parts of Speech":"NOUN","Tamil Words":"mullu","Irula Words":"mullu","Toda Words":"","Meaning":"A stiff, sharp-pointed woody projection on the stem or other part of a plant"},
{"English Words":"Till (preposition & conjunction)","Parts of Speech":"PREPOSITION & CONJUNCTION","Tamil Words":"varai","Irula Words":"vara","Toda Words":"","Meaning":"Less formal way of saying until"},
{"English Words":"Timber (n)","Parts of Speech":"NOUN","Tamil Words":"palakai","Irula Words":"palaka, nellikkaa maram, puucca maram, cuurippala maram, jiilimaram, kalaakkaay maram","Toda Words":"","Meaning":"Wood prepared for use in building and carpentry"},
{"English Words":"Time (n)","Parts of Speech":"NOUN","Tamil Words":"poluthu","Irula Words":"bo:tu","Toda Words":"","Meaning":"The indefinite continued progress of existence and events in the past, present, and future regarded as a whole"},
{"English Words":"Tired (v)","Parts of Speech":"VERB","Tamil Words":"co:rvu","Irula Words":"compal","Toda Words":"","Meaning":"in need of sleep or rest; weary"},
{"English Words":"To don’t allow","Parts of Speech":"","Tamil Words":"maruttatarku","Irula Words":"belventatukku","Toda Words":"","Meaning":""},
{"English Words":"To house","Parts of Speech":"","Tamil Words":"vettirkku","Irula Words":"ku:rekku","Toda Words":"a;s","Meaning":""},
{"English Words":"To the forest","Parts of Speech":"","Tamil Words":"kattirku","Irula Words":"kadukku","Toda Words":"","Meaning":""},
{"English Words":"Today (adv)","Parts of Speech":"ADVERB","Tamil Words":"inru","Irula Words":"indu, intu","Toda Words":"","Meaning":"On or in the course of this present day"},
{"English Words":"Told","Parts of Speech":"","Tamil Words":"conna:rkal","Irula Words":"conne:mu","Toda Words":"","Meaning":"Past and past participle of tell (communicate information to someone in spoken or written words)"},
{"English Words":"Tongue (n)","Parts of Speech":"NOUN","Tamil Words":"na:kku","Irula Words":"na:kku, na:k","Toda Words":"noy","Meaning":"The fleshy muscular organ in the mouth of a mammal, used for tasting, licking, swallowing, and (in humans) articulating speech"},
{"English Words":"Tooth (n)","Parts of Speech":"NOUN","Tamil Words":"pal","Irula Words":"be:lu , bellu","Toda Words":"pas","Meaning":"Each of a set of hard, bony enamel-coated structures in the jaws of most vertebrates, used for biting and chewing"},
{"English Words":"Top of the tree","Parts of Speech":"","Tamil Words":"ucci maram, curuli maram, araḷi maram","Irula Words":"muṭi maram, curilippu: maram, aralippu: maram","Toda Words":"","Meaning":"The head of a plant"},
{"English Words":"Tortoise (n)","Parts of Speech":"NOUN","Tamil Words":"a:me","Irula Words":"e:me","Toda Words":"","Meaning":"A slow-moving typically herbivorous land reptile of warm climates, enclosed in a scaly or leathery domed shell into which it can retract its head and thick legs"},
{"English Words":"Town (n)","Parts of Speech":"NOUN","Tamil Words":"u:r ","Irula Words":"patti","Toda Words":"","Meaning":"A  built-up area with a name, defined boundaries, and local government, that is larger than a village and generally smaller than a city"},
{"English Words":"Tree (n)","Parts of Speech":"NOUN","Tamil Words":"maram","Irula Words":"mer:, mara: ","Toda Words":"me:n","Meaning":"A woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground"},
{"English Words":"Trouser (n)","Parts of Speech":"NOUN","Tamil Words":"tavusar ","Irula Words":"trouasour","Toda Words":"","Meaning":"An outer garment covering the body from the waist to the ankles, with a separate part for each leg"},
{"English Words":"Trumpet (n)","Parts of Speech":"NOUN","Tamil Words":"na:yaṉam","Irula Words":"piikki, kokelu","Toda Words":"","Meaning":"A brass musical instrument with a flared bell and a bright, penetrating tone"},
{"English Words":"Tuber (n)","Parts of Speech":"NOUN","Tamil Words":"kiḻaṅku","Irula Words":"kaca:nku, kiḻa:ṅku, kecangu","Toda Words":"","Meaning":"A much thickened underground part of a stem or rhizome, e.g. in the potato, serving as a food reserve and bearing buds from which new plants arise"},
{"English Words":"Turmeric (n)","Parts of Speech":"NOUN","Tamil Words":"mañcaḷ","Irula Words":"menja:, manja:, manja, mañca","Toda Words":"","Meaning":"A bright yellow aromatic powder obtained from the rhizome of a plant of the ginger family, used for flavouring and colouring in Asian cooking and formerly as a fabric dye"},
{"English Words":"Two","Parts of Speech":"","Tamil Words":"irandu","Irula Words":"randu","Toda Words":"e:d","Meaning":"Number 2"},
{"English Words":"Type of birds","Parts of Speech":"","Tamil Words":"","Irula Words":"kuruvi , parave","Toda Words":"","Meaning":""},
{"English Words":"Tyre (n)","Parts of Speech":"","Tamil Words":"tayar","Irula Words":"tayaru","Toda Words":"","Meaning":"A rubber covering, typically inflated or surrounding an inflated inner tube, placed round a wheel to form a soft contact with the road"},
{"English Words":"Teeth","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"parh","Meaning":""},
{"English Words":"To join cloths","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"kuttkuṭittiye:","Meaning":""},
{"English Words":"thunder","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"iṟy","Meaning":""},
{"English Words":"to sharpen","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aroy-","Meaning":""},
{"English Words":"that much","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"atk","Meaning":""},
{"English Words":"then","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"atfok","Meaning":""},
{"English Words":"to shut","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aṟt","Meaning":""},
{"English Words":"tortoise","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"a:my","Meaning":""},
{"English Words":"To stich","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"kutti","Meaning":""},
{"English Words":"To take","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"a:ph","Meaning":""},
{"English Words":"To take the thread","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"nu:ra:hf","Meaning":""},
{"English Words":"two","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"e:ḍ","Meaning":""},
{"English Words":"to take out the potatoes","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"ki:sa:ttiye:","Meaning":""},
{"English Words":"To plant Potatoes","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"ki:soče:","Meaning":""},
{"English Words":"To make line in cultivation (paar pidithal)","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"po:rveče","Meaning":""},
{"English Words":"To crush sand","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"kaṭiotič","Meaning":""},
{"English Words":"to spray fertiliser","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"madustiye:","Meaning":""},
{"English Words":"to sack","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"mu:ṭkoḍuttiye:","Meaning":""},
{"English Words":"To put manure","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"kupo:rumeṭitiye:","Meaning":""},
{"English Words":"To dig wing the fork","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"muḷmettče: ","Meaning":""},
{"English Words":"Thread","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"nu:rh","Meaning":""},
{"English Words":"Ugly (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"aciṅkam","Irula Words":"mooca","Toda Words":"","Meaning":"Unpleasant or repulsive, especially in appearance"},
{"English Words":"Umberla (n)","Parts of Speech":"NOUN","Tamil Words":"kotai","Irula Words":"kote:","Toda Words":"","Meaning":"A device consisting of a circular canopy of cloth on a folding metal frame supported by a central rod, used as protection against rain"},
{"English Words":"Uncle (n)","Parts of Speech":"NOUN","Tamil Words":"maman               ","Irula Words":"ma;mana, ma:man     ","Toda Words":"","Meaning":"The brother of one's father or mother or the husband of one's aunt"},
{"English Words":"Unknown place","Parts of Speech":"","Tamil Words":"enkaiyo:, enkaiyo","Irula Words":"e:nko:, eko","Toda Words":"","Meaning":""},
{"English Words":"Untie (v)","Parts of Speech":"VERB","Tamil Words":"aviḻ","Irula Words":"untikkoNṭu va:","Toda Words":"","Meaning":"Undo or unfasten (something that is tied or tied up)"},
{"English Words":"Up (adv)","Parts of Speech":"ADVERB","Tamil Words":"e:ṟu","Irula Words":"meleru, meṭṭeeru","Toda Words":"","Meaning":"Towards a higher place or position"},
{"English Words":"Urad Dhal (n)","Parts of Speech":"NOUN","Tamil Words":"uḷuntu","Irula Words":"lontu","Toda Words":"","Meaning":"One kind of Dhal"},
{"English Words":"Us (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"nammai","Irula Words":"emme:","Toda Words":"","Meaning":"Used by a speaker to refer to himself or herself and one or more other people as the object of a verb or preposition"},
{"English Words":"urgent","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"afso:rm","Meaning":""},
{"English Words":"Veranda (n)","Parts of Speech":"NOUN","Tamil Words":"tiṉṉai","Irula Words":"tinne","Toda Words":"","Meaning":"A roofed platform along the outside of a house, level with the ground floor"},
{"English Words":"Vessel (n)","Parts of Speech":"NOUN","Tamil Words":"uṇavu camaikkap payaṉpaṭum pa:ttiram","Irula Words":"coru peeci, ca:ru peeci","Toda Words":"purh","Meaning":"A ship or large boat"},
{"English Words":"Village hamlet","Parts of Speech":"","Tamil Words":"u:r","Irula Words":"pati","Toda Words":"","Meaning":"A type of village settlement"},
{"English Words":"Virgin (n)","Parts of Speech":"NOUN","Tamil Words":"kanniben","Irula Words":"u:ni","Toda Words":"","Meaning":"A person who has never had sexual intercourse"},
{"English Words":"Vomite (v)","Parts of Speech":"VERB","Tamil Words":"vanti","Irula Words":"kaNNantaNNi","Toda Words":"","Meaning":"Eject matter from the stomach through the mouth"},
{"English Words":"","Parts of Speech":"","Tamil Words":"Va:tti","Irula Words":"va:ntu, vara:ntu","Toda Words":"","Meaning":""},
{"English Words":"Vessel used for churning butter","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"taṭṭi","Meaning":""},
{"English Words":"Walk (v)","Parts of Speech":"VERB","Tamil Words":"naṭa","Irula Words":"naṭa","Toda Words":"","Meaning":"Move at a regular pace by lifting and setting down each foot in turn, never having both feet off the ground at once"},
{"English Words":"Wash (v)","Parts of Speech":"VERB","Tamil Words":"kaḻuvu, alacu","Irula Words":"keturu, ala:cu","Toda Words":"","Meaning":"Clean with water and, typically, soap or detergent"},
{"English Words":"Wasp (n)","Parts of Speech":"NOUN","Tamil Words":"kuḷavi","Irula Words":"ka:ṭṭu tumpi","Toda Words":"","Meaning":""},
{"English Words":"Waste things","Parts of Speech":"","Tamil Words":"kuppai","Irula Words":"kuppe:","Toda Words":"","Meaning":""},
{"English Words":"We (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"na:nkal, n:im","Irula Words":"na:nka, na:mu, na:viri","Toda Words":"","Meaning":"Used by a speaker to refer to himself or herself and one or more other people considered together"},
{"English Words":"We are seeing","Parts of Speech":"","Tamil Words":"pa:rkiro:m","Irula Words":"pa:kkila:","Toda Words":"","Meaning":""},
{"English Words":"Weak (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"varam","Irula Words":"vara","Toda Words":"","Meaning":"Lacking the power to perform physically demanding tasks; having little physical strength or energy"},
{"English Words":"Went (v)","Parts of Speech":"VERB","Tamil Words":"po:iy","Irula Words":"po:yi","Toda Words":"","Meaning":"Past of go (move from one place to another; travel)"},
{"English Words":"What reason","Parts of Speech":"","Tamil Words":"ennakaranam","Irula Words":"ena:ka:rana","Toda Words":"","Meaning":""},
{"English Words":"When (adv)","Parts of Speech":"ADVERB","Tamil Words":"eppoluthu","Irula Words":"eppa","Toda Words":"etfok","Meaning":"At what time"},
{"English Words":"Where  it from","Parts of Speech":"","Tamil Words":"etil","Irula Words":"eguga","Toda Words":"","Meaning":""},
{"English Words":"Which ","Parts of Speech":"Determiner","Tamil Words":"etarku","Irula Words":"ena:ku","Toda Words":"","Meaning":"Asking for information specifying one or more people or things from a definite set"},
{"English Words":"Which day","Parts of Speech":"","Tamil Words":"ennaikku","Irula Words":"enikku","Toda Words":"","Meaning":""},
{"English Words":"White fly (n)","Parts of Speech":"NOUN","Tamil Words":"i:cal","Irula Words":"pu:le","Toda Words":"","Meaning":""},
{"English Words":"Why (adv)","Parts of Speech":"ADVERB","Tamil Words":"e:n","Irula Words":"e:","Toda Words":"e:ḏ","Meaning":"For what reason or purpose"},
{"English Words":"Why asked","Parts of Speech":"","Tamil Words":"ke:kkura:I","Irula Words":"kekku","Toda Words":"","Meaning":""},
{"English Words":"Why called","Parts of Speech":"","Tamil Words":"ennattukku","Irula Words":"e:lekka:","Toda Words":"","Meaning":""},
{"English Words":"Wife (n)","Parts of Speech":"NOUN","Tamil Words":"maṉaivi","Irula Words":"pombale, pondri, manaivi, ponṭukka:ri","Toda Words":"","Meaning":"A married woman considered in relation to her spouse"},
{"English Words":"Will come","Parts of Speech":"","Tamil Words":"varukirennenru, varum","Irula Words":"varugentu, varukaum","Toda Words":"","Meaning":""},
{"English Words":"Will go","Parts of Speech":"","Tamil Words":"po:gum","Irula Words":"po:ka","Toda Words":"","Meaning":""},
{"English Words":"Wipe (v)","Parts of Speech":"VERB","Tamil Words":"tuṭai","Irula Words":"toṭattiṭu","Toda Words":"","Meaning":"Clean or dry (something) by rubbing with a cloth, a piece of paper, or one's hand"},
{"English Words":"Wish (v)","Parts of Speech":"VERB","Tamil Words":"a:cai","Irula Words":"a:ca","Toda Words":"","Meaning":"Feel or express a strong desire or hope for something that cannot or probably will not happen"},
{"English Words":"With her","Parts of Speech":"","Tamil Words":"irunten","Irula Words":"irunte","Toda Words":"","Meaning":""},
{"English Words":"With me","Parts of Speech":"","Tamil Words":"enno;du","Irula Words":"emmmo:du","Toda Words":"","Meaning":""},
{"English Words":"With us","Parts of Speech":"","Tamil Words":"enkalo:du","Irula Words":"emunkalo:du","Toda Words":"","Meaning":""},
{"English Words":"With you","Parts of Speech":"","Tamil Words":"unnoodu","Irula Words":"ninnoodu","Toda Words":"","Meaning":""},
{"English Words":"Woman (n)","Parts of Speech":"NOUN","Tamil Words":"pillai","Irula Words":"pulle","Toda Words":"","Meaning":"A female of a specified nationality or origin"},
{"English Words":"Wont bite","Parts of Speech":"","Tamil Words":"katikka:thu","Irula Words":"katikka;","Toda Words":"","Meaning":""},
{"English Words":"Wont come","Parts of Speech":"","Tamil Words":"varamatta:n","Irula Words":"varama:tte:","Toda Words":"","Meaning":""},
{"English Words":"Worm (n)","Parts of Speech":"NOUN","Tamil Words":"puḻu","Irula Words":"pu:vvu","Toda Words":"","Meaning":"Any of a number of creeping or burrowing invertebrate animals with long, slender soft bodies and no limbs"},
{"English Words":"Wring (v)","Parts of Speech":"VERB","Tamil Words":"puḻi","Irula Words":"piinturu","Toda Words":"","Meaning":"Squeeze and twist (something) to force liquid from it"},
{"English Words":"Wall","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"kyo:fh","Meaning":""},
{"English Words":"where","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"e:l/e:nk","Meaning":""},
{"English Words":"wave","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"aly","Meaning":""},
{"English Words":"Window","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"somel","Meaning":""},
{"English Words":"White","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"pedith","Meaning":""},
{"English Words":"Year (n)","Parts of Speech":"NOUN","Tamil Words":"varudam","Irula Words":"varuca","Toda Words":"","Meaning":"The time taken by the earth to make one revolution around the sun"},
{"English Words":"Yesterday (adv)","Parts of Speech":"ADVERB","Tamil Words":"ne:rru ","Irula Words":"naga:ttu, nega:ttu","Toda Words":"","Meaning":"On the day before today"},
{"English Words":"You (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"ni:, unnai, ni:nkal","Irula Words":"ni:nu, Nine, ne:viri","Toda Words":"","Meaning":"Used to refer to the person or people that the speaker is addressing"},
{"English Words":"Younger (adj)","Parts of Speech":"ADJECTIVE","Tamil Words":"ilannan","Irula Words":"u:na;","Toda Words":"","Meaning":"Comparitive adjective of young (having lived or existed for only a short time)"},
{"English Words":"Younger brother","Parts of Speech":"","Tamil Words":"tampi","Irula Words":"tambika, tambi, entampi","Toda Words":"","Meaning":""},
{"English Words":"Younger sister","Parts of Speech":"","Tamil Words":"taṅkai","Irula Words":"tange, paranthava, ammini, ammi, tanga","Toda Words":"","Meaning":""},
{"English Words":"Yours (pronoun)","Parts of Speech":"PRONOUN","Tamil Words":"unnutayathu, unkalutayate","Irula Words":"nittuta:tu, ni:tto:","Toda Words":"","Meaning":"Used to refer to a thing or things belonging to or associated with the person or people that the speaker is addressing"},
{"English Words":"Yellow","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"argin","Meaning":""},
{"English Words":"yet","Parts of Speech":"","Tamil Words":"","Irula Words":"","Toda Words":"inm","Meaning":""}];

$(document).ready(function() {
    $('#example').DataTable( {
        data: dataSet,        
        columns: [            
            { title: "English Words", "data":"English Words" },            
            { title: "Parts of Speech", "data":"Parts of Speech" },            
            { title: "Tamil Words", "data":"Tamil Words" },            
            { title: "Irula Words", "data":"Irula Words" },            
            { title: "Toda Words", "data":"Toda Words" },            
            { title: "Meaning", "data":"Meaning" },            
        ]
    } );
} );
